use rusqlite::Connection;
use serde_json::{json, Value};
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

fn rpc(id:u64,method:&str,params:Value)->Value{json!({"jsonrpc":"2.0","id":id,"method":method,"params":params})}
fn tool(id:u64,name:&str,args:Value)->Value{rpc(id,"tools/call",json!({"name":name,"arguments":args}))}

fn run(root:&Path,requests:&[Value])->Vec<Value>{
    let mut child=Command::new(env!("CARGO_BIN_EXE_narada-mcp-surfaces")).args(["--surface-id","site-loop","--site-root",&root.to_string_lossy()]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().expect("spawn");
    {let input=child.stdin.as_mut().expect("stdin");for request in requests{writeln!(input,"{request}").expect("write")}}
    let output=child.wait_with_output().expect("wait"); assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr).chars().take(2000).collect::<String>());
    String::from_utf8(output.stdout).expect("utf8").lines().filter(|line|!line.trim().is_empty()).map(|line|serde_json::from_str(line).expect("response")).collect()
}
fn response<'a>(values:&'a[Value],id:u64)->&'a Value{values.iter().find(|value|value["id"]==id).expect("response id")}
fn structured(value:&Value)->&Value{value.pointer("/result/structuredContent").expect("structured")}
fn assert_bounded(schema:&Value,path:&str){if schema.get("type").and_then(Value::as_str)==Some("string")&&schema.get("enum").is_none(){assert!(schema.get("maxLength").and_then(Value::as_u64).is_some(),"unbounded string {path}")}if schema.get("type").and_then(Value::as_str)==Some("array"){assert!(schema.get("maxItems").and_then(Value::as_u64).is_some(),"unbounded array {path}")}if let Some(properties)=schema.get("properties").and_then(Value::as_object){for(name,child)in properties{assert_bounded(child,&format!("{path}/{name}"))}}if let Some(items)=schema.get("items"){assert_bounded(items,&format!("{path}/*"))}}

#[test]
fn site_loop_public_protocol_is_closed_bounded_and_real(){
    let root=std::env::temp_dir().join(format!("narada-site-loop-stdio-{}",uuid::Uuid::new_v4()));fs::create_dir_all(root.join(".narada/capabilities")).expect("root");fs::create_dir_all(root.join("docs")).expect("docs");fs::write(root.join("docs/guide.md"),"bounded guide").expect("guide");
    fs::write(root.join(".narada/capabilities/site-loop-config.json"),serde_json::to_vec(&json!({"schema":"narada.site_loop.config.v2","loop_id":"stdio.loop","site_id":"stdio","display_name":"Stdio","resident":{"agent_id":"stdio.resident","role":"resident"},"scheduler":{},"recovery_plan":{"steps":[],"guardrails":[]},"docs":[{"path":"docs/guide.md","description":"Guide"}],"tests":{"rust_version":{"command":"rustc","args":["--version"]}},"persistence":{"schema":"narada.site_loop.persistence.v2","evidence_root":".ai/site-loop-evidence","raw_retention_days":7,"summary_retention_days":90,"inline_summary_bytes":16384,"compression":"gzip"}})).expect("config")).expect("config");
    fs::create_dir_all(root.join(".ai/tmp/mcp-outputs/workspace")).expect("outputs");fs::write(root.join(".ai/tmp/mcp-outputs/workspace/proof-output.json"),serde_json::to_vec(&json!({"schema":"narada.mcp_output_ref.v1","tool_name":"fixture","full_output":{"value":"ok"}})).expect("output")).expect("output");
    let db=Connection::open(root.join(".ai/task-lifecycle.db")).expect("db");db.execute_batch("CREATE TABLE site_loop_runs(run_id TEXT,loop_id TEXT,status TEXT,dry_run INTEGER,started_at TEXT,finished_at TEXT,summary_json TEXT,error_json TEXT,evidence_ref TEXT,evidence_sha256 TEXT,evidence_bytes INTEGER);CREATE TABLE site_loop_step_runs(step_run_id TEXT,run_id TEXT,step_id TEXT,status TEXT,started_at TEXT,finished_at TEXT,input_refs_json TEXT,output_refs_json TEXT,input_ref_count INTEGER,output_ref_count INTEGER,input_refs_digest TEXT,output_refs_digest TEXT,evidence_json TEXT,error_json TEXT,evidence_ref TEXT,evidence_sha256 TEXT,evidence_bytes INTEGER);CREATE TABLE site_loop_escalations(escalation_id TEXT,loop_id TEXT,directive_id TEXT,classification TEXT,status TEXT,envelope_id TEXT,created_at TEXT,acknowledged_at TEXT,acknowledged_by TEXT,ack_reason TEXT,escalation_summary_json TEXT,escalation_ref TEXT,escalation_sha256 TEXT,escalation_bytes INTEGER);CREATE TABLE site_loop_control(loop_id TEXT PRIMARY KEY,enabled INTEGER,paused INTEGER,mode TEXT,reason TEXT,updated_at TEXT);INSERT INTO site_loop_runs VALUES('run-1','stdio.loop','completed',0,'2026-01-01T00:00:00Z','2026-01-01T00:00:01Z','{}',NULL,NULL,NULL,NULL);INSERT INTO site_loop_step_runs VALUES('step-1','run-1','prepare','completed','2026-01-01T00:00:00Z',NULL,'[]','[]',0,0,NULL,NULL,'{}',NULL,NULL,NULL,NULL);INSERT INTO site_loop_escalations VALUES('attention-1','stdio.loop',NULL,'proof','opened','envelope-1','2026-01-01T00:00:00Z',NULL,NULL,NULL,'{}',NULL,NULL,NULL);INSERT INTO site_loop_control VALUES('stdio.loop',1,0,'running',NULL,'2026-01-01T00:00:00Z');").expect("schema");drop(db);
    let catalog=run(&root,&[rpc(1,"tools/list",json!({}))]);let tools=response(&catalog,1).pointer("/result/tools").and_then(Value::as_array).expect("tools");assert_eq!(tools.len(),26);
    for entry in tools{let name=entry["name"].as_str().expect("name");let schema=&entry["inputSchema"];assert_eq!(schema["title"],format!("{name}.input"));assert_eq!(schema["additionalProperties"],false);assert_bounded(schema,name)}
    let invalid=tools.iter().enumerate().map(|(index,entry)|tool(1000+index as u64,entry["name"].as_str().unwrap(),json!({"__unexpected_contract_probe__":true}))).collect::<Vec<_>>();let invalid_responses=run(&root,&invalid);for(index,entry)in tools.iter().enumerate(){assert!(response(&invalid_responses,1000+index as u64).get("error").is_some(),"{} accepted unknown input",entry["name"])}
    let calls=vec![
        tool(10,"site_loop_guidance",json!({})),tool(11,"site_loop_doctor",json!({})),tool(12,"site_docs_list",json!({})),tool(13,"site_docs_show",json!({"path":"docs/guide.md"})),tool(14,"site_test_list",json!({})),tool(15,"site_test_run",json!({"selector":"rust_version"})),tool(16,"site_loop_config_validate",json!({})),tool(17,"site_loop_operator_affordances",json!({})),tool(18,"site_loop_status",json!({})),tool(19,"site_loop_unified_status",json!({})),tool(20,"site_loop_recovery_plan",json!({})),tool(21,"site_loop_health",json!({})),tool(22,"site_loop_operating_status",json!({})),tool(23,"site_loop_proof_status",json!({})),tool(24,"site_loop_readiness",json!({})),tool(25,"site_loop_coherence",json!({})),tool(26,"site_loop_runs_list",json!({"limit":10})),tool(27,"site_loop_run_show",json!({"run_id":"run-1"})),tool(28,"site_loop_output_show",json!({"ref":"mcp_output:proof-output","limit":100})),tool(29,"site_loop_attention_list",json!({"limit":10})),tool(30,"site_loop_attention_show",json!({"attention_id":"envelope-1"})),tool(31,"site_loop_attention_ack",json!({"attention_id":"envelope-1","reason":"reviewed","acknowledged_by":"stdio.test"})),tool(32,"site_loop_control_set",json!({"enabled":true,"reason":"stdio proof","changed_by":"stdio.test"})),tool(33,"site_loop_proof_run",json!({"proof_kind":"resident_production","ensure_resident":false})),tool(34,"site_loop_run_once",json!({"dry_run":true})),tool(35,"site_loop_recovery_drill",json!({"reason":"stdio boundary proof","timeout_ms":1}))];
    let results=run(&root,&calls);for id in 10..=34{assert!(response(&results,id).get("error").is_none(),"normal call {id}: {}",response(&results,id))}assert_eq!(structured(response(&results,33))["status"],"started");assert_eq!(structured(response(&results,34))["dry_run"],true);assert_eq!(response(&results,35).pointer("/error/data/code").or_else(||response(&results,35).pointer("/error/code")).and_then(Value::as_str),Some("recovery_drill_live_carrier_required"));
    fs::remove_dir_all(root).expect("cleanup");
}
