include!("engine/parts/01.rs");
include!("engine/impl_parts/01.rs");
include!("engine/impl_parts/02.rs");
include!("engine/impl_parts/03.rs");
include!("engine/impl_parts/04.rs");
include!("engine/impl_parts/05.rs");
include!("engine/impl_parts/06.rs");
include!("engine/impl_parts/07.rs");
include!("engine/impl_parts/08.rs");
include!("engine/impl_parts/09.rs");
include!("engine/impl_parts/10.rs");
include!("engine/impl_parts/11.rs");
include!("engine/impl_parts/12.rs");
include!("engine/impl_parts/13.rs");
include!("engine/impl_parts/14.rs");
include!("engine/impl_parts/15.rs");
include!("engine/impl_parts/16.rs");
include!("engine/impl_parts/17.rs");
include!("engine/impl_parts/18.rs");
include!("engine/impl_parts/19.rs");
include!("engine/impl_parts/20.rs");
include!("engine/impl_parts/21.rs");
include!("engine/impl_parts/22.rs");
include!("engine/impl_parts/23.rs");
include!("engine/impl_parts/24.rs");
include!("engine/impl_parts/25.rs");
include!("engine/impl_parts/26.rs");
include!("engine/impl_parts/27.rs");
include!("engine/impl_parts/28.rs");
include!("engine/impl_parts/29.rs");
include!("engine/impl_parts/30.rs");
include!("engine/impl_parts/31.rs");
include!("engine/impl_parts/32.rs");

#[cfg(test)]
mod tests {
    include!("engine/tests/parts/01.rs");
    include!("engine/tests/parts/02.rs");
    include!("engine/tests/parts/03.rs");
    include!("engine/tests/parts/04.rs");
    include!("engine/tests/parts/05.rs");
    include!("engine/tests/parts/06.rs");
    include!("engine/tests/parts/07.rs");
    include!("engine/tests/parts/08.rs");
    include!("engine/tests/parts/09.rs");
    include!("engine/tests/parts/10.rs");
}
