#![recursion_limit = "512"]

mod authority;
mod browser_control_authority;
mod calendar;
mod cloudflare_carrier_authority;
mod codex_app_server_broker;
mod delegated_task;
mod graph_authority;
mod graph_mail_authority;
mod host_contracts;
mod launcher;
mod local_admin;
mod mailbox;
mod mailbox_sync;
mod operator_surface_authority;
mod operator_console;
mod operator_console_runtime;
mod project_state_authority;
mod quota_authority;
mod runtime_introspection;
mod scheduler;
mod scheduler_activation;
mod simple_surfaces;
mod site_coherence;
mod site_inbox;
mod site_lifecycle_authority;
mod site_registry_authority;
mod sop;
mod sop_authority;
mod sop_engine;
mod speech_authority;
mod surface_feedback;
mod worker_delegation;

include!("main/parts/01.rs");
include!("main/parts/02.rs");
include!("main/parts/03.rs");
include!("main/parts/04.rs");
include!("main/parts/05.rs");
include!("main/parts/06.rs");
include!("main/parts/07.rs");
include!("main/parts/08.rs");
