fn remove_selector(target: &mut Item, selector: &str) -> Result<(), String> {
    let segments = pointer_segments(selector)?;
    let (last, parents) = segments
        .split_last()
        .ok_or_else(|| format!("managed_selector_invalid:{selector}"))?;
    let mut current = target;
    for parent in parents {
        let Some(next) = current
            .as_table_like_mut()
            .and_then(|table| table.get_mut(parent))
        else {
            return Ok(());
        };
        current = next;
    }
    if let Some(table) = current.as_table_like_mut() {
        table.remove(last);
    }
    Ok(())
}

fn normalize_emitted_text(text: &str) -> Vec<u8> {
    let normalized = text
        .trim_start_matches('\u{feff}')
        .replace("\r\n", "\n")
        .replace('\r', "\n");
    let mut normalized = normalized.trim_end_matches('\n').to_string();
    normalized.push('\n');
    normalized.into_bytes()
}

pub fn merge_codex_configuration(
    existing: Option<&[u8]>,
    desired: &[u8],
    previous_selectors: &[String],
    current_selectors: &[String],
) -> Result<Vec<u8>, String> {
    let desired_text = std::str::from_utf8(desired)
        .map_err(|error| error.to_string())?
        .trim_start_matches('\u{feff}');
    let desired_doc = desired_text
        .parse::<DocumentMut>()
        .map_err(|error| error.to_string())?;
    let mut target_doc = match existing {
        Some(bytes) => {
            let text = std::str::from_utf8(bytes)
                .map_err(|error| error.to_string())?
                .trim_start_matches('\u{feff}')
                .replace(
                    "# Generated by narada-mcp-materializer. Do not hand-edit; changes will be overwritten on next materialize.",
                    "# Narada manages only recorded MCP and carrier policy settings; other Codex settings are preserved.",
                );
            text.parse::<DocumentMut>()
                .map_err(|error| error.to_string())?
        }
        None => desired_doc.clone(),
    };
    let mut effective_previous_selectors = previous_selectors.to_vec();
    if effective_previous_selectors.iter().any(|selector| selector == "/mcp_servers") {
        effective_previous_selectors.retain(|selector| selector != "/mcp_servers");
        if let Some(servers) = target_doc
            .get("mcp_servers")
            .and_then(|item| item.as_table_like())
        {
            effective_previous_selectors.extend(
                servers
                    .iter()
                    .map(|(name, _)| name)
                    .filter(|name| name.starts_with("narada-"))
                    .map(|name| format!("/mcp_servers/{}", pointer_escape(name))),
            );
        }
    }
    effective_previous_selectors.sort();
    effective_previous_selectors.dedup();
    for selector in &effective_previous_selectors {
        if !current_selectors.contains(selector) {
            remove_selector(target_doc.as_item_mut(), selector)?;
        }
    }
    for selector in current_selectors {
        set_selector(target_doc.as_item_mut(), desired_doc.as_item(), selector)?;
    }
    Ok(normalize_emitted_text(&target_doc.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Deserialize)]
    struct VectorCorpus {
        vectors: Vec<FingerprintVector>,
    }

    #[derive(Deserialize)]
    struct FingerprintVector {
        id: String,
        carrier_kind: String,
        content: String,
        selectors: Vec<String>,
        expected_bytes_sha256: String,
        expected_managed_sha256: String,
    }

    #[test]
    fn fingerprint_vectors_are_stable() {
        let corpus: VectorCorpus =
            serde_json::from_str(include_str!("../../../../contracts/fingerprint-vectors.json")).unwrap();
        for vector in corpus.vectors {
            let description = describe_config(
                &vector.carrier_kind,
                vector.content.as_bytes(),
                &vector.selectors,
            )
            .unwrap();
            println!(
                "VECTOR {} {} {}",
                vector.id,
                description.config_artifact.bytes_sha256,
                description.managed_projection.sha256
            );
            if !vector.expected_bytes_sha256.is_empty() {
                assert_eq!(
                    description.config_artifact.bytes_sha256, vector.expected_bytes_sha256,
                    "{} bytes",
                    vector.id
                );
            }
            if !vector.expected_managed_sha256.is_empty() {
                assert_eq!(
                    description.managed_projection.sha256, vector.expected_managed_sha256,
                    "{} managed",
                    vector.id
                );
            }
        }
    }

    #[test]
    fn codex_projection_ignores_formatting_and_unmanaged_values() {
        let selectors = vec!["/mcp_servers".to_string()];
        let lf = b"model = \"a\"\n[mcp_servers.fixture]\ncommand = \"x\"\n";
        let crlf = b"model = \"b\"\r\n\r\n[mcp_servers.fixture]\r\ncommand=\"x\"\r\n";
        assert_eq!(
            managed_projection("codex", lf, &selectors).unwrap().sha256,
            managed_projection("codex", crlf, &selectors)
                .unwrap()
                .sha256,
        );
        assert_ne!(
            config_artifact(lf).unwrap().bytes_sha256,
            config_artifact(crlf).unwrap().bytes_sha256
        );
    }

    #[test]
    fn codex_merge_preserves_unmanaged_settings_and_removes_retired_selectors() {
        let existing = b"model = \"gpt\"\n[plugins.old]\nenabled = true\ncustom = 1\n[mcp_servers.old]\ncommand = \"old\"\n";
        let desired = b"[features]\napps = false\n[mcp_servers.new]\ncommand = \"new\"\n";
        let previous = vec![
            "/mcp_servers".to_string(),
            "/plugins/old/enabled".to_string(),
        ];
        let current = vec!["/features/apps".to_string(), "/mcp_servers".to_string()];
        let merged = String::from_utf8(
            merge_codex_configuration(Some(existing), desired, &previous, &current).unwrap(),
        )
        .unwrap();
        assert!(merged.contains("model = \"gpt\""));
        assert!(merged.contains("custom = 1"));
        assert!(!merged.contains("enabled = true"));
        assert!(merged.contains("[mcp_servers.new]"));
        assert!(!merged.contains("[mcp_servers.old]"));
        assert!(!merged.contains('\r'));
        assert!(merged.ends_with('\n'));
    }

    #[test]
    fn legacy_whole_table_ownership_is_narrowed_during_generic_name_migration() {
        let existing = b"[mcp_servers.user-owned]\ncommand = \"user\"\n[mcp_servers.narada-site-old-local-filesystem]\ncommand = \"old\"\n";
        let desired = b"[mcp_servers.local-filesystem]\ncommand = \"new\"\n";
        let merged = String::from_utf8(
            merge_codex_configuration(
                Some(existing),
                desired,
                &["/mcp_servers".to_string()],
                &["/mcp_servers/local-filesystem".to_string()],
            )
            .unwrap(),
        )
        .unwrap();
        assert!(merged.contains("[mcp_servers.user-owned]"));
        assert!(merged.contains("[mcp_servers.local-filesystem]"));
        assert!(!merged.contains("narada-site-old-local-filesystem"));
    }
}
