//! Domain-independent append-only event-ledger machinery implementing the
//! `narada.event-ledger.v1` regime (see `docs/event-ledger-format.md`):
//! hash-chained immutable JSON event files are the only authority, SQLite
//! projections are disposable rebuilds, and every mutation is an idempotent,
//! fail-hard append serialized by an exclusive authority lock.
//!
//! The crate owns no domain concepts. Consuming surfaces supply their error
//! envelope schema string, ledger layout (directory + filename prefix), event
//! envelope fields, projection DDL, and per-event projection fold.

pub mod args;
pub mod chain;
pub mod digest;
pub mod error;
pub mod io;
pub mod ledger;
pub mod lock;
pub mod projection;
pub mod query;

pub use error::ErrorSchema;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{json, Map, Value};
    use std::fs;
    use std::path::PathBuf;
    use uuid::Uuid;

    const TEST_SCHEMA: ErrorSchema = ErrorSchema("narada.test.error.v1");

    fn temp_root(tag: &str) -> PathBuf {
        std::env::temp_dir().join(format!("narada-ledger-test-{tag}-{}", Uuid::new_v4()))
    }

    fn test_layout(root: &std::path::Path) -> ledger::LedgerLayout {
        ledger::LedgerLayout::new(root.join("ledger"), "ev")
    }

    fn append_test_event(
        layout: &ledger::LedgerLayout,
        payload: &str,
        idempotency_key: Option<&str>,
    ) -> ledger::AppendOutcome {
        ledger::append_event(TEST_SCHEMA, layout, "event_hash", None, idempotency_key, |ctx| {
            json!({
                "schema":"narada.test.event.v1",
                "sequence":ctx.sequence,
                "event_id":ctx.event_id,
                "previous_hash":ctx.previous_hash,
                "payload":payload,
                "idempotency_key":idempotency_key,
                "occurred_at":digest::now()
            })
        })
        .expect("append test event")
    }

    #[test]
    fn digest_golden_vector_locks_insertion_order_convention() {
        // Generated by the pre-extraction epistemic-graph implementation; this
        // constant locks the insertion-order digest convention byte-for-byte.
        let digest = digest::digest_value(
            TEST_SCHEMA,
            &json!({"alpha":1,"beta":"x","gamma":[1,2],"nested":{"z":true,"a":null}}),
        )
        .expect("digest");
        assert_eq!(
            digest,
            "842ba011c408262fbfeb355119a2fc3c2b7c5e042daeeebe31def45f47508226"
        );
        let forward = digest::digest_value(TEST_SCHEMA, &json!({"a":1,"b":2})).unwrap();
        let reversed = digest::digest_value(TEST_SCHEMA, &json!({"b":2,"a":1})).unwrap();
        assert_ne!(forward, reversed);
    }

    #[test]
    fn digest_helpers_match_legacy_formats() {
        assert_eq!(digest::safe_name("a b:c/d_e-f"), "abcd_e-f");
        assert_eq!(digest::safe_name(&"x".repeat(200)).len(), 120);
        assert_eq!(
            digest::sha256(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        let stamp = digest::now();
        time::OffsetDateTime::parse(&stamp, &time::format_description::well_known::Rfc3339)
            .expect("now() is RFC 3339");
    }

    #[test]
    fn io_writes_are_create_new_and_durable() {
        let root = temp_root("io");
        fs::create_dir_all(&root).unwrap();
        let path = root.join("record.json");
        io::write_new_json(TEST_SCHEMA, &path, &json!({"a":1})).expect("write new json");
        let raw = fs::read_to_string(&path).unwrap();
        assert!(raw.ends_with("}\n"));
        assert_eq!(io::read_json(TEST_SCHEMA, &path).unwrap(), json!({"a":1}));
        let conflict = io::write_new_json(TEST_SCHEMA, &path, &json!({"a":2}))
            .expect_err("create_new refuses existing records");
        assert_eq!(conflict["code"], "immutable_record_exists");
        let marker = root.join("idem-key.txt");
        io::write_new(TEST_SCHEMA, &marker, b"event-id").expect("write marker");
        assert_eq!(fs::read_to_string(&marker).unwrap(), "event-id");
        io::write_replace_json(TEST_SCHEMA, &path, &json!({"a":3})).expect("replace json");
        assert_eq!(io::read_json(TEST_SCHEMA, &path).unwrap(), json!({"a":3}));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn authority_lock_serializes_and_reports_contention() {
        let root = temp_root("lock");
        let locks = root.join("locks");
        let value = lock::with_authority_lock(
            TEST_SCHEMA,
            &locks,
            "ledger",
            lock::AuthorityLockPolicy::default(),
            || Ok(42),
        )
        .expect("uncontended lock");
        assert_eq!(value, 42);

        use fs2::FileExt;
        let lock_path = locks.join("ledger.lock");
        let held = std::fs::OpenOptions::new()
            .create(true)
            .read(true)
            .write(true)
            .open(&lock_path)
            .unwrap();
        held.try_lock_exclusive().expect("hold lock");
        let busy = lock::with_authority_lock(
            TEST_SCHEMA,
            &locks,
            "ledger",
            lock::AuthorityLockPolicy {
                timeout: std::time::Duration::from_millis(150),
                poll: std::time::Duration::from_millis(10),
            },
            || Ok(()),
        )
        .expect_err("contended lock refuses");
        assert_eq!(busy["code"], "authority_busy");
        FileExt::unlock(&held).unwrap();
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn appended_events_chain_verify_and_head_tracks_last_event() {
        let root = temp_root("ledger");
        let layout = test_layout(&root);
        fs::create_dir_all(&layout.directory).unwrap();
        let first = append_test_event(&layout, "one", Some("key-one"));
        let second = append_test_event(&layout, "two", Some("key-two"));
        assert_eq!(first.sequence, 1);
        assert_eq!(second.sequence, 2);
        assert_eq!(second.event["previous_hash"], json!(first.event_hash));
        ledger::verify(TEST_SCHEMA, &layout, "event_hash").expect("chain verifies");
        assert_eq!(
            ledger::head(TEST_SCHEMA, &layout, "event_hash").unwrap(),
            Some(second.event_hash.clone())
        );
        let files = ledger::files(TEST_SCHEMA, &layout).unwrap();
        assert_eq!(files.len(), 2);
        assert!(layout.idempotency_marker_path("key-one").exists());
        assert_eq!(
            fs::read_to_string(layout.idempotency_marker_path("key-one")).unwrap(),
            first.event_id
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn head_cas_refuses_stale_or_unexpected_heads() {
        let root = temp_root("cas");
        let layout = test_layout(&root);
        fs::create_dir_all(&layout.directory).unwrap();
        let first = append_test_event(&layout, "one", None);
        let head = first.event_hash.clone();
        ledger::append_event(
            TEST_SCHEMA,
            &layout,
            "event_hash",
            Some(Some(head.as_str())),
            None,
            |ctx| {
                json!({"schema":"narada.test.event.v1","sequence":ctx.sequence,"event_id":ctx.event_id,"previous_hash":ctx.previous_hash})
            },
        )
        .expect("matching head admits");
        let stale = ledger::append_event(
            TEST_SCHEMA,
            &layout,
            "event_hash",
            Some(Some(head.as_str())),
            None,
            |ctx| {
                json!({"schema":"narada.test.event.v1","sequence":ctx.sequence,"event_id":ctx.event_id,"previous_hash":ctx.previous_hash})
            },
        )
        .expect_err("stale head refuses");
        assert_eq!(stale["code"], "ledger_head_conflict");
        let unexpected_empty = ledger::append_event(
            TEST_SCHEMA,
            &layout,
            "event_hash",
            Some(None),
            None,
            |ctx| {
                json!({"schema":"narada.test.event.v1","sequence":ctx.sequence,"event_id":ctx.event_id,"previous_hash":ctx.previous_hash})
            },
        )
        .expect_err("expected-empty head refuses on a non-empty ledger");
        assert_eq!(unexpected_empty["code"], "ledger_head_conflict");
        assert_eq!(ledger::files(TEST_SCHEMA, &layout).unwrap().len(), 2);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn idempotency_scan_recovers_events_after_marker_loss() {
        let root = temp_root("idem");
        let layout = test_layout(&root);
        fs::create_dir_all(&layout.directory).unwrap();
        let appended = append_test_event(&layout, "one", Some("lost-marker"));
        fs::remove_file(layout.idempotency_marker_path("lost-marker")).unwrap();
        let found = ledger::find_event_by_idempotency(TEST_SCHEMA, &layout, "lost-marker")
            .expect("scan")
            .expect("event recovered by ledger scan");
        assert_eq!(found["event_id"], json!(appended.event_id));
        assert!(
            ledger::find_event_by_idempotency(TEST_SCHEMA, &layout, "never-seen")
                .unwrap()
                .is_none()
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn tampered_or_missing_events_fail_verification() {
        let root = temp_root("tamper");
        let layout = test_layout(&root);
        fs::create_dir_all(&layout.directory).unwrap();
        append_test_event(&layout, "one", None);
        append_test_event(&layout, "two", None);
        let files = ledger::files(TEST_SCHEMA, &layout).unwrap();
        let mut event = io::read_json(TEST_SCHEMA, &files[0]).unwrap();
        event["payload"] = json!("tampered");
        fs::write(&files[0], serde_json::to_vec_pretty(&event).unwrap()).unwrap();
        let failure = ledger::verify(TEST_SCHEMA, &layout, "event_hash")
            .expect_err("tampered event refuses");
        assert_eq!(failure["code"], "ledger_hash_invalid");

        let root = temp_root("gap");
        let layout = test_layout(&root);
        fs::create_dir_all(&layout.directory).unwrap();
        append_test_event(&layout, "one", None);
        append_test_event(&layout, "two", None);
        fs::remove_file(ledger::files(TEST_SCHEMA, &layout).unwrap()[0].clone()).unwrap();
        let failure = ledger::verify(TEST_SCHEMA, &layout, "event_hash")
            .expect_err("missing event refuses");
        assert_eq!(failure["code"], "ledger_sequence_invalid");
        let _ = fs::remove_dir_all(root);
        let _ = fs::remove_dir_all(temp_root("tamper"));
    }

    #[test]
    fn projection_rebuild_swaps_atomically_and_refuses_tampered_ledgers() {
        let root = temp_root("projection");
        let layout = test_layout(&root);
        fs::create_dir_all(&layout.directory).unwrap();
        append_test_event(&layout, "one", None);
        append_test_event(&layout, "two", None);
        let projection_path = root.join("projection.sqlite");
        let apply = |tx: &rusqlite::Transaction, event: &Value, event_id: &str| {
            tx.execute(
                "insert or replace into items values(?1,?2,?3)",
                rusqlite::params![event["payload"].as_str().unwrap(), event["sequence"].as_u64().unwrap(), event_id],
            )
            .map_err(|_| json!({"code":"test_apply_failed"}))?;
            Ok(())
        };
        projection::rebuild_projection(
            TEST_SCHEMA,
            &layout,
            "event_hash",
            &projection_path,
            "create table items(id text primary key,sequence integer not null,event_id text not null);",
            apply,
        )
        .expect("rebuild");
        assert!(projection_path.exists());
        assert!(!projection_path.with_extension("sqlite.next").exists());
        let db = rusqlite::Connection::open(&projection_path).unwrap();
        let count: i64 = db
            .query_row("select count(*) from items", [], |row| row.get(0))
            .unwrap();
        assert_eq!(count, 2);
        drop(db);
        let before = fs::read(&projection_path).unwrap();

        let files = ledger::files(TEST_SCHEMA, &layout).unwrap();
        let mut event = io::read_json(TEST_SCHEMA, &files[0]).unwrap();
        event["payload"] = json!("tampered");
        fs::write(&files[0], serde_json::to_vec_pretty(&event).unwrap()).unwrap();
        let failure = projection::rebuild_projection(
            TEST_SCHEMA,
            &layout,
            "event_hash",
            &projection_path,
            "create table items(id text primary key,sequence integer not null,event_id text not null);",
            apply,
        )
        .expect_err("tampered ledger refuses rebuild");
        assert_eq!(failure["code"], "ledger_hash_invalid");
        assert_eq!(fs::read(&projection_path).unwrap(), before);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn chain_verify_supports_alternate_hash_and_ordinal_fields() {
        let root = temp_root("chain");
        let claims = root.join("claims");
        fs::create_dir_all(&claims).unwrap();
        let mut previous: Option<String> = None;
        for value in [40_u64, 41] {
            let mut claim = json!({
                "schema":"narada.test.claim.v1",
                "value":value,
                "previous_claim_hash":previous
            });
            let hash = digest::digest_value(TEST_SCHEMA, &claim).unwrap();
            claim
                .as_object_mut()
                .unwrap()
                .insert("claim_hash".into(), json!(hash.clone()));
            io::write_new_json(
                TEST_SCHEMA,
                &claims.join(format!("claim-{value:020}.json")),
                &claim,
            )
            .unwrap();
            previous = Some(hash);
        }
        let files = fs::read_dir(&claims)
            .unwrap()
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .collect::<Vec<_>>();
        let spec = chain::ChainSpec {
            hash_field: "claim_hash",
            previous_hash_field: "previous_claim_hash",
            ordinal_field: "value",
            ordinal_start: 40,
            missing_hash: chain::Refusal::new("test_claim_missing", "claim lacks claim_hash"),
            ordinal_invalid: chain::Refusal::new("test_claim_invalid", "claim chain is invalid"),
            link_invalid: chain::Refusal::new("test_claim_invalid", "claim chain is invalid"),
            hash_invalid: chain::Refusal::new("test_claim_invalid", "claim chain is invalid"),
        };
        let items = chain::verify_files(TEST_SCHEMA, &files, &spec).expect("claim chain verifies");
        assert_eq!(items.len(), 2);
        let recomputed = chain::recompute_hash(TEST_SCHEMA, &items[0], "claim_hash")
            .unwrap()
            .expect("hash present");
        assert_eq!(recomputed.stored, recomputed.computed);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn args_helpers_enforce_required_fields_and_bounds() {
        let args = Map::from_iter([
            ("actor".into(), json!("tester")),
            ("authority_basis".into(), json!({"kind":"test"})),
        ]);
        assert_eq!(
            args::required(TEST_SCHEMA, &args, "actor").unwrap(),
            "tester"
        );
        let missing = args::required(TEST_SCHEMA, &args, "absent").expect_err("missing");
        assert_eq!(missing["code"], "required_argument_missing");
        let object = args::required_object(TEST_SCHEMA, &args, "authority_basis", 8192, "authority_basis")
            .expect("bounded object");
        assert_eq!(object["kind"], "test");
        let oversized = Map::from_iter([(
            "authority_basis".into(),
            json!({"blob":"x".repeat(9000)}),
        )]);
        let failure =
            args::required_object(TEST_SCHEMA, &oversized, "authority_basis", 8192, "authority_basis")
                .expect_err("oversized object");
        assert_eq!(failure["code"], "argument_too_large");
        assert_eq!(
            failure["message"],
            "authority_basis exceeds the bounded 8192-byte envelope"
        );
        assert_eq!(args::optional_u64(TEST_SCHEMA, &args, "start_at", 1).unwrap(), 1);
        let invalid = Map::from_iter([("limit".into(), json!("high"))]);
        assert!(
            args::optional_u64(TEST_SCHEMA, &invalid, "limit", 100)
                .expect_err("non-integer limit")["code"]
                == "argument_invalid"
        );
        assert_eq!(args::page_limit(TEST_SCHEMA, &args).unwrap(), 100);
        let over = Map::from_iter([("limit".into(), json!(101))]);
        assert_eq!(
            args::page_limit(TEST_SCHEMA, &over).expect_err("limit over 100")["code"],
            "page_limit_invalid"
        );
        assert_eq!(args::page_offset(TEST_SCHEMA, &args).unwrap(), 0);
        let _ = args;
    }
}
