// Generated by Narada carrier materialization. Do not edit.
import { readFileSync } from "node:fs";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createInterface } from "node:readline";

type ServerConfig = {
  name: string;
  command: string;
  args: string[];
  enabled: boolean;
  startupTimeoutMs: number;
};

type JsonRpcResponse = {
  id?: number;
  result?: any;
  error?: { code?: number; message?: string; data?: unknown };
};

type StartupRuntime = {
  loader: string;
  proxy: string;
};

type StartupAuthority = {
  site: string;
  siteRoot: string;
  identity: string;
  lifecycle: string;
};

export type NaradaMariciInboxPollResult = {
  count: number;
  previousCursor: number;
  newCursor: number;
  source: "epistemic_graph_communication";
};

export type NaradaMariciInboxPollRequest = {
  siteRoot: "C:/Users/andrey/src/marici";
  sinceSequence: number;
  requestId: string;
  resolve: (result: NaradaMariciInboxPollResult) => void;
  reject: (error: Error) => void;
};

export const NARADA_MARICI_INBOX_POLL_EVENT = "narada:mcp:marici-inbox-poll";
const NARADA_SESSION_IDENTITY_ENTRY = "narada-session-identity.v2";
const LEGACY_MARICI_SESSION_IDENTITY_ENTRY = "narada-marici-session-identity";

type NaradaSessionIdentityState =
  | { status: "admitted"; identity: string; sessionId: string; changedAt: string; source: "operator_slash_command" }
  | { status: "cleared"; identity: null; sessionId: string; changedAt: string; source: "operator_slash_command" };

type EffectiveNaradaIdentity = {
  identity: string;
  source: "operator_slash_command" | "carrier_admission";
};

function normalizeNaradaIdentity(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const identity = value.trim();
  return identity.length > 0
    && identity.length <= 200
    && /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(identity)
    ? identity
    : null;
}

const SERVERS: ServerConfig[] = __NARADA_PI_MCP_SERVERS__;
const PROTOCOL_VERSION = "2026-07-28";
const MAX_BOOTSTRAP_TOOLS = 80;
const MAX_BOOTSTRAP_SCHEMA_CHARS = 120_000;
function shouldBootstrapServer(config: ServerConfig): boolean {
  return config.enabled && config.name === "mcp-loader";
}

function optionValue(args: string[], option: string): string | null {
  const index = args.indexOf(option);
  return index >= 0 && typeof args[index + 1] === "string" ? args[index + 1] : null;
}

function startupAuthority(configs: ServerConfig[]): StartupAuthority {
  let admission: any = null;
  for (const config of configs) {
    const admissionPath = optionValue(config.args, "--binding-admission-path");
    if (!admissionPath) continue;
    try {
      admission = JSON.parse(readFileSync(admissionPath, "utf8"));
      break;
    } catch {
      // The diagnostic must never make MCP startup fail.
    }
  }
  const context = admission?.authority_context ?? {};
  const identity = process.env.NARADA_AGENT_ID?.trim()
    || context.identity?.agent_id
    || context.identity?.status
    || "unknown";
  return {
    site: process.env.NARADA_SITE_ID?.trim() || admission?.site_id || "unknown",
    siteRoot: process.env.NARADA_SITE_ROOT?.trim() || "not-bound",
    identity,
    lifecycle: context.lifecycle_participation || "unknown",
  };
}

function runtimeStatus(result: any): string {
  const structured = result?.structuredContent ?? result?.result?.structuredContent ?? {};
  return structured?.runtime_freshness?.status
    || structured?.freshness?.status
    || "unknown";
}

async function inspectStartupRuntime(client: McpClient, tools: any[]): Promise<StartupRuntime> {
  const runtime: StartupRuntime = { loader: "unknown", proxy: "unknown" };
  const calls: Array<[keyof StartupRuntime, string]> = [
    ["loader", "mcp_loader_runtime_status"],
    ["proxy", "mcp_runtime_proxy_status"],
  ];
  for (const [key, toolName] of calls) {
    if (!tools.some((tool) => tool?.name === toolName)) continue;
    try {
      runtime[key] = runtimeStatus(await client.request("tools/call", {
        name: toolName,
        arguments: {},
      }, 5_000));
    } catch {
      runtime[key] = "unknown";
    }
  }
  return runtime;
}

function startupRestartOwner(state: { mcp: string; runtime: StartupRuntime }): string {
  if (state.mcp === "loading") return "pending";
  if (state.mcp !== "attached") return "session_then_carrier_or_runtime_supervisor";
  if (state.runtime.loader === "stale" || state.runtime.proxy === "stale") return "carrier_or_runtime_supervisor";
  if (state.runtime.loader === "unknown" || state.runtime.proxy === "unknown") return "inspect_before_restart";
  return "none";
}

function startupDiagnostic(
  authority: StartupAuthority,
  state: { mcp: string; runtime: StartupRuntime; remediation: string },
): string {
  return [
    "Narada MCP startup",
    `carrier=pi`,
    `mcp=${state.mcp}`,
    `loader=${state.runtime.loader}`,
    `proxy=${state.runtime.proxy}`,
    `site=${authority.site}`,
    `site_root=${authority.siteRoot}`,
    `identity=${authority.identity}`,
    `lifecycle=${authority.lifecycle}`,
    `restart_owner=${startupRestartOwner(state)}`,
    `remediation=${state.remediation}`,
  ].join("; ");
}

function startupRemediation(authority: StartupAuthority, runtime: StartupRuntime, mcp: string): string {
  const actions: string[] = [];
  if (mcp !== "attached") {
    actions.push("retry the session restart");
    actions.push("if persistent, ask the carrier/runtime supervisor to restart mcp-loader");
  } else if (runtime.loader === "stale" || runtime.proxy === "stale") {
    actions.push("ask the carrier/runtime supervisor to restart the stale loader/proxy");
  } else if (runtime.loader === "unknown" || runtime.proxy === "unknown") {
    actions.push("inspect mcp-loader freshness before lifecycle mutation");
  }
  if (authority.identity === "anonymous" || authority.identity === "unknown") {
    actions.push("provide a mechanically admitted Site identity for named operations");
  }
  return actions.length > 0 ? actions.join("; ") : "none";
}

function resultText(result: any): string {
  return (Array.isArray(result?.content) ? result.content : [])
    .filter((block: any) => block?.type === "text" && typeof block.text === "string")
    .map((block: any) => block.text)
    .join("\n");
}

function isOutputPage(value: any): boolean {
  const schema = value?.schema;
  return schema === "narada.mcp_loader.result_page.v1"
    || (typeof schema === "string" && schema.endsWith("output_page.v1"));
}

function projectSchemaLeaseForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.schema_lease.v1") return undefined;
  const projection: Record<string, any> = {
    schema: value.schema,
    status: value.status,
    tool_name: value.tool_name,
    schema_lease: value.schema_lease,
  };
  if (Object.prototype.hasOwnProperty.call(value, "connection_id")) {
    projection.connection_id = value.connection_id;
  }
  if (Object.prototype.hasOwnProperty.call(value, "surface_id")) {
    projection.surface_id = value.surface_id;
  }
  if (Object.prototype.hasOwnProperty.call(value, "input_contract")) {
    projection.input_contract = value.input_contract;
  } else if (Object.prototype.hasOwnProperty.call(value, "tool_contract")) {
    projection.tool_contract = value.tool_contract;
  }
  return projection;
}

function projectSchemaLeaseBatchForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.schema_lease_batch.v1" || !Array.isArray(value.leases)) return undefined;
  const leases = value.leases.map((lease: any) => {
    const projection: Record<string, any> = {};
    for (const field of ["tool_name", "schema_lease"]) {
      if (typeof lease?.[field] === "string") projection[field] = lease[field];
    }
    if (Object.prototype.hasOwnProperty.call(lease ?? {}, "input_contract")) projection.input_contract = lease.input_contract;
    return projection;
  });
  const projection: Record<string, any> = { schema: value.schema, status: value.status, leases };
  for (const field of ["connection_id", "surface_handle"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  if (typeof value.lease_count === "number") projection.lease_count = value.lease_count;
  return projection;
}

function projectRuntimeFreshnessForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.runtime_freshness.v1") return undefined;
  const projection: Record<string, any> = { schema: value.schema, status: value.status };
  if (typeof value?.reload_required === "boolean") projection.reload_required = value.reload_required;
  const needsAttention = value.status !== "current" || value.reload_required === true;
  if (needsAttention && typeof value?.freshness_scope === "string") projection.freshness_scope = value.freshness_scope;
  if (needsAttention && Array.isArray(value?.reasons) && value.reasons.length > 0) projection.reasons = value.reasons;
  if (needsAttention && value?.reload_action && typeof value.reload_action === "object") {
    const action: Record<string, any> = {};
    for (const field of ["owner", "availability", "capability", "tool_name"]) {
      if (typeof value.reload_action[field] === "string") action[field] = value.reload_action[field];
    }
    if (Object.keys(action).length > 0) projection.reload_action = action;
  }
  return projection;
}

function projectConnectionInventoryForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.connection_inventory.v1" || !Array.isArray(value.connections)) return undefined;
  const projection: Record<string, any> = { schema: value.schema, status: value.status };
  for (const field of ["connection_count", "available_slots", "live_count"]) {
    if (typeof value[field] === "number") projection[field] = value[field];
  }
  projection.connections = value.connections.map((connection: any) => {
    const compact: Record<string, any> = {};
    for (const field of ["connection_id", "binding_id", "generation_id", "surface_id", "liveness"]) {
      if (typeof connection?.[field] === "string") compact[field] = connection[field];
    }
    if (typeof connection?.pending_request_count === "number" && connection.pending_request_count > 0) {
      compact.pending_request_count = connection.pending_request_count;
    }
    const restart = connection?.actions?.restart;
    if (restart && typeof restart === "object") {
      if (typeof restart.actuator === "string") compact.restart_owner = restart.actuator;
      else if (typeof restart.tool_name === "string") compact.restart_tool = restart.tool_name;
    }
    return compact;
  });
  const freshness = value.runtime_freshness;
  if (freshness && typeof freshness === "object" && (freshness.status !== "current" || freshness.reload_required === true)) {
    const compact: Record<string, any> = {};
    for (const field of ["status", "reload_required"]) {
      if (Object.prototype.hasOwnProperty.call(freshness, field)) compact[field] = freshness[field];
    }
    if (Object.keys(compact).length > 0) projection.runtime_freshness = compact;
  }
  return projection;
}

function projectSurfaceHandleOpenedForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.surface_handle_opened.v1") return undefined;
  const projection: Record<string, any> = { schema: value.schema, status: value.status };
  for (const field of ["surface_handle", "handle_scope", "binding_id", "generation_id", "site_root", "surface_id", "runtime_kind"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  for (const field of ["handle_survives_child_restart", "handle_survives_loader_restart"]) {
    if (typeof value?.[field] === "boolean") projection[field] = value[field];
  }
  if (typeof value?.tool_count === "number") projection.tool_count = value.tool_count;
  return projection;
}

function projectSiteSurfacesForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.site_surfaces.v1" || !Array.isArray(value.surfaces)) return undefined;
  const projection: Record<string, any> = { schema: value.schema, status: value.status };
  if (typeof value.site_root === "string") projection.site_root = value.site_root;
  if (typeof value.surface_count === "number") projection.surface_count = value.surface_count;
  projection.surfaces = value.surfaces.map((surface: any) => {
    const compact: Record<string, any> = {};
    for (const field of ["binding_id", "surface_id"]) {
      if (typeof surface?.[field] === "string") compact[field] = surface[field];
    }
    return compact;
  });
  return projection;
}

function projectSiteToolInventoryFindingForModel(value: any): any {
  const projection: Record<string, any> = {};
  for (const field of [
    "surface_id",
    "status",
    "declared_count",
    "observed_count",
    "missing_from_fabric",
    "extra_in_fabric",
    "duplicate_declared_tools",
    "duplicate_observed_tools",
    "unclassified_observed_tools",
  ]) {
    if (Object.prototype.hasOwnProperty.call(value ?? {}, field)) projection[field] = value[field];
  }
  return projection;
}

function projectSiteToolInventoryForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.site_tool_inventory_check.v1") return undefined;
  const projection: Record<string, any> = {
    schema: value.schema,
    status: value.status,
    checked_surface_count: value.checked_surface_count,
    violation_count: value.violation_count,
    observation_ref: value.observation_ref,
  };
  if (Object.prototype.hasOwnProperty.call(value, "finding_status_counts")) {
    projection.finding_status_counts = value.finding_status_counts;
  }
  if (Array.isArray(value.findings)) {
    projection.findings = value.findings.map(projectSiteToolInventoryFindingForModel);
  }
  return projection;
}

function projectSurfaceAttachedForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.surface_attached.v1") return undefined;
  const projection: Record<string, any> = {
    schema: value.schema,
    status: value.status,
    connection_id: value.connection_id,
    logical_connection_id: value.logical_connection_id,
    generation_id: value.generation_id,
    site_root: value.site_root,
    surface_id: value.surface_id,
    binding_id: value.binding_id,
    runtime_kind: value.runtime_kind,
    tool_count: value.tool_count,
  };
  if (value.server_info && typeof value.server_info === "object") {
    projection.server_info = {};
    for (const field of ["name", "version"]) {
      if (typeof value.server_info[field] === "string") projection.server_info[field] = value.server_info[field];
    }
  }
  if (value.tool_discovery && typeof value.tool_discovery === "object") {
    projection.tool_discovery = {};
    if (typeof value.tool_discovery.tool_name === "string") projection.tool_discovery.tool_name = value.tool_discovery.tool_name;
  }
  if (value.tool_inspection && typeof value.tool_inspection === "object") {
    projection.tool_inspection = {};
    if (Array.isArray(value.tool_inspection.required_arguments)) projection.tool_inspection.required_arguments = value.tool_inspection.required_arguments;
  }
  const lifecycle = value.runtime_lifecycle;
  if (lifecycle && typeof lifecycle === "object") {
    projection.runtime_lifecycle = {};
    for (const field of ["managed_by", "restartable", "restartability_status", "restart_scope", "session_restart_required"]) {
      if (Object.prototype.hasOwnProperty.call(lifecycle, field)) projection.runtime_lifecycle[field] = lifecycle[field];
    }
  }
  const freshness = value.runtime_freshness;
  if (freshness && typeof freshness === "object") {
    projection.runtime_freshness = {};
    for (const field of ["status", "reload_required"]) {
      if (Object.prototype.hasOwnProperty.call(freshness, field)) projection.runtime_freshness[field] = freshness[field];
    }
  }
  return projection;
}

function compactGitSummary(value: any): any {
  if (typeof value === "string") return value;
  if (!value || typeof value !== "object") return undefined;
  const summary: Record<string, any> = {};
  for (const field of ["staged_count", "unstaged_count", "untracked_count", "conflict_count", "matching_path_count", "clean"]) {
    if (Object.prototype.hasOwnProperty.call(value, field)) summary[field] = value[field];
  }
  return Object.keys(summary).length > 0 ? summary : undefined;
}

function copyGitDiagnostic(value: any, projection: Record<string, any>): void {
  for (const field of ["error", "message", "reason", "remediation"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  if (value?.push_remediation && typeof value.push_remediation === "object") {
    const remediation: Record<string, any> = {};
    for (const field of ["status", "reason", "action", "message"]) {
      if (typeof value.push_remediation[field] === "string") remediation[field] = value.push_remediation[field];
    }
    if (Object.keys(remediation).length > 0) projection.push_remediation = remediation;
  }
}

function compactGitStatusProjection(value: any): any {
  const projection: Record<string, any> = { schema: value.schema, status: value.status };
  for (const field of ["repository_root", "branch", "upstream", "ahead", "behind", "clean"]) {
    if (Object.prototype.hasOwnProperty.call(value ?? {}, field)) projection[field] = value[field];
  }
  for (const field of ["staged", "unstaged", "untracked", "conflicts"]) {
    if (Array.isArray(value?.[field])) projection[field] = value[field];
  }
  const summary = compactGitSummary(value?.summary);
  if (summary !== undefined) projection.summary = summary;
  if (value?.push_target && typeof value.push_target === "object" && value.push_target.status !== "resolved") {
    const target: Record<string, any> = {};
    for (const field of ["status", "remote", "branch", "source"]) {
      if (typeof value.push_target[field] === "string") target[field] = value.push_target[field];
    }
    if (Object.keys(target).length > 0) projection.push_target = target;
  }
  copyGitDiagnostic(value, projection);
  return projection;
}

function projectGitResultForModel(value: any): any | undefined {
  const schema = value?.schema;
  if (schema === "narada.git.status.v1") return compactGitStatusProjection(value);
  if (schema === "narada.git.add.v1" || schema === "narada.git.unstage.v1") {
    const projection: Record<string, any> = { schema, status: value.status };
    for (const field of ["operation", "paths", "work_scope_ref"]) {
      if (Array.isArray(value?.[field]) || typeof value?.[field] === "string") projection[field] = value[field];
    }
    const summary = compactGitSummary(value?.summary);
    if (summary !== undefined) projection.summary = summary;
    if (value?.post_status && typeof value.post_status === "object") projection.post_status = compactGitStatusProjection(value.post_status);
    copyGitDiagnostic(value, projection);
    return projection;
  }
  if (schema === "narada.git.commit.v1") {
    const projection: Record<string, any> = { schema, status: value.status };
    for (const field of ["commit", "work_scope_ref"]) {
      if (typeof value?.[field] === "string") projection[field] = value[field];
    }
    for (const field of ["committed_files"]) {
      if (Array.isArray(value?.[field])) projection[field] = value[field];
    }
    if (typeof value?.committed_file_count === "number") projection.committed_file_count = value.committed_file_count;
    const summary = compactGitSummary(value?.summary);
    if (summary !== undefined) projection.summary = summary;
    if (value?.post_status && typeof value.post_status === "object") projection.post_status = compactGitStatusProjection(value.post_status);
    copyGitDiagnostic(value, projection);
    return projection;
  }
  if (schema === "narada.git.push.v1") {
    const projection: Record<string, any> = { schema, status: value.status };
    for (const field of ["remote", "branch", "commit", "work_scope_ref"]) {
      if (typeof value?.[field] === "string") projection[field] = value[field];
    }
    const summary = compactGitSummary(value?.summary);
    if (summary !== undefined) projection.summary = summary;
    copyGitDiagnostic(value, projection);
    return projection;
  }
  if (schema === "narada.git.work_scope.v1") {
    const projection: Record<string, any> = { schema, status: value.status };
    for (const field of ["work_scope_ref", "owner_id", "authority", "expires_at"]) {
      if (typeof value?.[field] === "string") projection[field] = value[field];
    }
    if (Array.isArray(value?.allowed_paths)) projection.allowed_paths = value.allowed_paths;
    if (typeof value?.mutation_started === "boolean") projection.mutation_started = value.mutation_started;
    copyGitDiagnostic(value, projection);
    return projection;
  }
  if (schema === "narada.git.work_scope_end.v1") {
    const projection: Record<string, any> = { schema, status: value.status };
    for (const field of ["work_scope_ref", "owner_id"]) {
      if (typeof value?.[field] === "string") projection[field] = value[field];
    }
    if (Array.isArray(value?.released_paths)) projection.released_paths = value.released_paths;
    if (typeof value?.mutation_started === "boolean") projection.mutation_started = value.mutation_started;
    copyGitDiagnostic(value, projection);
    return projection;
  }
  return undefined;
}

function projectStructuredCommandResultForModel(value: any): any | undefined {
  if (value?.schema !== "narada.structured_command.execution_result.v0") return undefined;
  const projection: Record<string, any> = { schema: value.schema, status: value.status };
  if (value.status === "running") {
    if (typeof value?.execution_ref === "string") projection.execution_ref = value.execution_ref;
    return projection;
  }
  for (const field of ["executed", "pending"]) {
    if (typeof value?.[field] === "boolean") projection[field] = value[field];
  }
  for (const field of ["execution_ref"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  if (typeof value?.exit_code === "number") projection.exit_code = value.exit_code;
  for (const field of ["stdout", "stderr"]) {
    if (typeof value?.[field] === "string" && value[field].length > 0) projection[field] = value[field];
  }
  for (const field of ["stdout_truncated", "stderr_truncated", "timed_out", "cancelled"]) {
    if (value?.[field] === true) projection[field] = true;
  }
  for (const field of ["stdout_next_offset", "stderr_next_offset"]) {
    if (typeof value?.[field] === "number") projection[field] = value[field];
  }
  for (const field of ["refusal_reasons", "remediation_hints"]) {
    if (Array.isArray(value?.[field]) && value[field].length > 0) projection[field] = value[field];
  }
  return projection;
}

function projectMcpLoaderToolsForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.tools.v1" || !Array.isArray(value.tools)) return undefined;
  const tools = value.tools
    .map((tool: any) => typeof tool?.name === "string" ? { name: tool.name } : undefined)
    .filter((tool: any): tool is { name: string } => tool !== undefined);
  const projection: Record<string, any> = { schema: value.schema, tools };
  for (const field of ["status", "connection_id", "surface_id"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  if (typeof value?.tool_count === "number") projection.tool_count = value.tool_count;
  const freshness = value.runtime_freshness;
  if (freshness && typeof freshness === "object" && (freshness.status !== "current" || freshness.reload_required === true)) {
    const compact: Record<string, any> = {};
    for (const field of ["status", "reload_required"]) {
      if (Object.prototype.hasOwnProperty.call(freshness, field)) compact[field] = freshness[field];
    }
    if (Array.isArray(freshness.reasons) && freshness.reasons.length > 0) compact.reasons = freshness.reasons;
    if (Object.keys(compact).length > 0) projection.runtime_freshness = compact;
  }
  const lifecycle = value.runtime_lifecycle;
  if (lifecycle && typeof lifecycle === "object" && lifecycle.restartability_status !== "available") {
    const compact: Record<string, any> = {};
    for (const field of ["restartability_status", "session_restart_required"]) {
      if (Object.prototype.hasOwnProperty.call(lifecycle, field)) compact[field] = lifecycle[field];
    }
    if (Object.keys(compact).length > 0) projection.runtime_lifecycle = compact;
  }
  return projection;
}

function projectLocalFilesystemGrepForModel(value: any): any | undefined {
  if (value?.schema !== "local.filesystem.grep.v1" || !Array.isArray(value.match_objects)) return undefined;
  const matchObjects = value.match_objects.map((match: any) => {
    const projection: Record<string, any> = {};
    for (const field of ["path", "line", "count", "text"]) {
      if (Object.prototype.hasOwnProperty.call(match ?? {}, field)) projection[field] = match[field];
    }
    return projection;
  });
  const projection: Record<string, any> = { schema: value.schema, status: value.status, match_objects: matchObjects };
  for (const field of ["output_mode", "snapshot_id"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  for (const field of ["offset", "limit", "count", "returned"]) {
    if (typeof value?.[field] === "number") projection[field] = value[field];
  }
  for (const field of ["count_exact", "has_more", "snapshot_complete"]) {
    if (typeof value?.[field] === "boolean") projection[field] = value[field];
  }
  if (value?.count_exact === false && typeof value?.count_semantics === "string") projection.count_semantics = value.count_semantics;
  if (Object.prototype.hasOwnProperty.call(value ?? {}, "next_offset")) projection.next_offset = value.next_offset;
  if (value?.no_match_diagnostics && typeof value.no_match_diagnostics === "object") {
    const diagnostics: Record<string, any> = {};
    for (const field of ["status", "remediation"]) {
      if (typeof value.no_match_diagnostics[field] === "string") diagnostics[field] = value.no_match_diagnostics[field];
    }
    if (Object.keys(diagnostics).length > 0) projection.no_match_diagnostics = diagnostics;
  }
  return projection;
}

function projectEpistemicGuidanceForModel(value: any): any | undefined {
  if (value?.schema !== "narada.epistemic.guidance.v2") return undefined;
  const projection: Record<string, any> = { schema: value.schema };
  if (typeof value?.purpose === "string") projection.purpose = value.purpose;
  if (Array.isArray(value.workflow)) {
    projection.workflow = value.workflow.map((step: any) => {
      const compact: Record<string, any> = {};
      if (typeof step?.step === "number") compact.step = step.step;
      if (typeof step?.tool === "string") compact.tool = step.tool;
      if (Array.isArray(step?.tools)) {
        const tools = step.tools.filter((tool: any) => typeof tool === "string");
        if (tools.length > 0) compact.tools = tools;
      }
      for (const field of ["preferred", "alternative", "manual_only"]) {
        if (typeof step?.[field] === "boolean") compact[field] = step[field];
      }
      return compact;
    });
  }
  if (Array.isArray(value.read_routing)) {
    const routes = value.read_routing
      .map((route: any) => typeof route?.tool === "string" ? { tool: route.tool } : undefined)
      .filter((route: any): route is { tool: string } => route !== undefined);
    if (routes.length > 0) projection.read_routing = routes;
  }
  const transport = value.payload_transport;
  if (transport && typeof transport === "object") {
    const compact: Record<string, any> = {};
    if (Array.isArray(transport.accepted_by)) compact.accepted_by = transport.accepted_by.filter((tool: any) => typeof tool === "string");
    if (transport.call_shape && typeof transport.call_shape === "object" && typeof transport.call_shape.payload_ref === "string") {
      compact.call_shape = { payload_ref: transport.call_shape.payload_ref };
    }
    for (const field of ["exclusive_form", "authority_rule"]) {
      if (typeof transport[field] === "string") compact[field] = transport[field];
    }
    if (Object.keys(compact).length > 0) projection.payload_transport = compact;
  }
  if (value.identity_rule && typeof value.identity_rule === "object" && typeof value.identity_rule.idempotency === "string") {
    projection.identity_rule = { idempotency: value.identity_rule.idempotency };
  }
  for (const field of ["concurrency_rule", "admission_meaning", "problem_policy"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  if (value.requested && typeof value.requested === "object") {
    const requested: Record<string, string> = {};
    for (const field of ["workflow", "tool"]) {
      if (typeof value.requested[field] === "string") requested[field] = value.requested[field];
    }
    if (Object.keys(requested).length > 0) projection.requested = requested;
  }
  return projection;
}

function projectMutationReceiptForModel(structured: any): any | undefined {
  if (structured?.schema === "local.filesystem.write_file.v1") {
    return {
      schema: structured.schema,
      status: structured.status,
      relative_path: structured.relative_path,
      size: structured.size,
      sha256: structured.sha256 ?? structured.after_sha256,
      before_sha256: structured.before_sha256,
      after_sha256: structured.after_sha256,
    };
  }
  if (structured?.schema === "narada.epistemic.submit_review_admit.v1") {
    const submission = structured.submission ?? {};
    const review = structured.review ?? {};
    const admission = structured.admission ?? {};
    return {
      schema: structured.schema,
      status: structured.status,
      proposal_id: submission.proposal_id ?? admission.proposal_id,
      proposal_digest: submission.proposal_digest,
      content_fingerprint: submission.content_fingerprint,
      operation_count: submission.operation_count,
      review_status: review.status,
      admission_status: admission.status,
      ledger_head: admission.ledger_head ?? admission.ledger_head_digest,
      review_gate_preserved: structured.review_gate_preserved,
      certifies_truth: structured.certifies_truth,
    };
  }
  return undefined;
}

function loaderControlPlaneProjectionForModel(value: any): any | undefined {
  return projectSurfaceAttachedForModel(value) ?? projectSurfaceHandleOpenedForModel(value) ?? projectRuntimeFreshnessForModel(value) ?? projectGitResultForModel(value) ?? projectStructuredCommandResultForModel(value) ?? projectMcpLoaderToolsForModel(value) ?? projectLocalFilesystemGrepForModel(value) ?? projectEpistemicGuidanceForModel(value) ?? projectMutationReceiptForModel(value) ?? projectEpistemicQueryForModel(value) ?? projectTeamWorkOverviewForModel(value) ?? projectConnectionInventoryForModel(value) ?? projectSiteSurfacesForModel(value) ?? projectSchemaLeaseBatchForModel(value) ?? projectSchemaLeaseForModel(value) ?? projectSiteToolInventoryForModel(value);
}

function projectEpistemicQueryForModel(value: any): any | undefined {
  if (value?.schema !== "narada.epistemic.query.v2" || !Array.isArray(value.items)) return undefined;
  const projection: Record<string, any> = { schema: value.schema, items: value.items };
  if (Object.prototype.hasOwnProperty.call(value, "status")) projection.status = value.status;
  for (const field of ["count", "returned_count"]) {
    if (typeof value[field] === "number") projection[field] = value[field];
  }
  if (typeof value.has_more === "boolean") projection.has_more = value.has_more;
  if (Object.prototype.hasOwnProperty.call(value, "next_cursor")) projection.next_cursor = value.next_cursor;
  return projection;
}

function projectTeamWorkOverviewForModel(value: any): any | undefined {
  if (value?.schema !== "narada.epistemic.team_work_overview.v1" || !Array.isArray(value.items)) return undefined;
  const projectItem = (item: any): any => {
    const row: Record<string, any> = {};
    for (const field of ["tree_id", "objective", "member", "status", "leaf", "latest_attributable_transition", "attribution_basis", "blocker_count", "directed_handoff_count"]) {
      if (Object.prototype.hasOwnProperty.call(item ?? {}, field)) row[field] = item[field];
    }
    if (item?.freshness && typeof item.freshness === "object") {
      row.freshness = {};
      for (const field of ["classification", "rule"]) {
        if (typeof item.freshness[field] === "string") row.freshness[field] = item.freshness[field];
      }
    }
    if (item?.live_presence && typeof item.live_presence === "object") {
      row.live_presence = {};
      for (const field of ["claimed", "capability"]) {
        if (Object.prototype.hasOwnProperty.call(item.live_presence, field)) row.live_presence[field] = item.live_presence[field];
      }
    }
    return row;
  };
  const projection: Record<string, any> = { schema: value.schema, status: value.status, items: value.items.map(projectItem) };
  if (typeof value.mode === "string") projection.mode = value.mode;
  for (const field of ["returned", "limit"]) {
    if (typeof value[field] === "number") projection[field] = value[field];
  }
  if (typeof value.has_more === "boolean") projection.has_more = value.has_more;
  if (Object.prototype.hasOwnProperty.call(value, "next_cursor")) projection.next_cursor = value.next_cursor;
  if (value.coverage && typeof value.coverage === "object") {
    const coverage: Record<string, any> = {};
    for (const field of ["complete", "total_matching", "omitted_count", "unattributed_active_tree_count"]) {
      if (Object.prototype.hasOwnProperty.call(value.coverage, field)) coverage[field] = value.coverage[field];
    }
    for (const field of ["partial_evidence_classes", "unavailable_evidence_classes"]) {
      if (Array.isArray(value.coverage[field]) && value.coverage[field].length > 0) coverage[field] = value.coverage[field];
    }
    if (Object.keys(coverage).length > 0) projection.coverage = coverage;
  }
  if (value.semantics && typeof value.semantics === "object") {
    const semantics: Record<string, any> = {};
    for (const field of ["frontier", "communications", "live_presence"]) {
      if (typeof value.semantics[field] === "string") semantics[field] = value.semantics[field];
    }
    if (Object.keys(semantics).length > 0) projection.semantics = semantics;
  }
  return projection;
}

function bodyOnlyProjectionText(structured: any): string | undefined {
  if (structured?.schema !== "narada.epistemic.query.v2" || structured.template !== "epistemic:inbox" || !Array.isArray(structured.items)) return undefined;
  return JSON.stringify(structured.items.map((item: any) => typeof item?.body === "string" ? item.body : ""));
}

function projectMcpLoaderToolResultForModel(value: any): any | undefined {
  if (value?.schema !== "narada.mcp_loader.tool_result.v1") return undefined;
  const summary = value.result_summary;
  const page = value.result;
  const projection: Record<string, any> = {
    schema: value.schema,
    status: typeof value.status === "string"
      ? value.status
      : typeof summary?.status === "string"
        ? summary.status
        : typeof page?.status === "string" ? page.status : "ok",
  };
  for (const field of ["connection_id", "surface_id"]) {
    if (typeof value?.[field] === "string") projection[field] = value[field];
  }
  if (typeof value?.result_bounded === "boolean") projection.result_bounded = value.result_bounded;
  if (summary && typeof summary === "object") {
    const compact: Record<string, any> = {};
    for (const field of [
      "schema",
      "status",
      "is_error",
      "count",
      "item_count",
      "finding_count",
      "tool_count",
      "ref",
      "output_ref",
      "next_offset",
      "truncated",
    ]) {
      if (Object.prototype.hasOwnProperty.call(summary, field)) {
        const candidate = summary[field];
        if (typeof candidate === "string" || typeof candidate === "number" || typeof candidate === "boolean" || candidate === null) {
          compact[field] = candidate;
        }
      }
    }
    if (Object.keys(compact).length > 0) projection.result_summary = compact;
  }
  const reference = typeof value?.details_ref === "string"
    ? value.details_ref
    : typeof page?.output_ref === "string"
      ? page.output_ref
      : typeof page?.ref === "string" ? page.ref : undefined;
  if (reference !== undefined) projection.details_ref = reference;
  const reader = typeof value?.details_reader === "string"
    ? value.details_reader
    : typeof page?.reader_tool === "string" ? page.reader_tool : undefined;
  if (reader !== undefined) projection.details_reader = reader;
  for (const field of ["next_offset", "transport_next_offset"]) {
    if (Object.prototype.hasOwnProperty.call(page ?? {}, field)) projection[field] = page[field];
  }
  return projection;
}

function projectParsedOutputValueForModel(value: any, depth = 0): string | undefined {
  if (depth > 4 || value === null || typeof value !== "object") return undefined;
  const bodyOnly = bodyOnlyProjectionText(value);
  if (bodyOnly !== undefined) return bodyOnly;
  const projection = loaderControlPlaneProjectionForModel(value);
  if (projection !== undefined) return JSON.stringify(projection);
  const nested: any[] = [value?.structuredContent, value?.result?.structuredContent];
  if (value?.schema === "narada.mcp_loader.tool_result.v1") nested.push(value.result);
  for (const candidate of nested) {
    if (candidate === undefined || candidate === value) continue;
    const projected = projectParsedOutputValueForModel(candidate, depth + 1);
    if (projected !== undefined) return projected;
  }
  const loaderResult = projectMcpLoaderToolResultForModel(value);
  if (loaderResult !== undefined) return JSON.stringify(loaderResult);
  if (isOutputPage(value) && typeof value.output_text === "string") {
    const projected = projectOutputPageTextForModel(value.output_text);
    if (projected !== value.output_text) return projected;
  }
  return undefined;
}

function projectOutputPageTextForModel(outputText: string): string {
  let current = outputText;
  for (let depth = 0; depth < 3; depth += 1) {
    let parsed: any;
    try {
      parsed = JSON.parse(current);
    } catch {
      return outputText;
    }
    const projection = projectParsedOutputValueForModel(parsed);
    if (projection !== undefined) return projection;
    if (!isOutputPage(parsed) || typeof parsed.output_text !== "string") return outputText;
    current = parsed.output_text;
  }
  return current;
}

function modelProjectionTextFromStructured(structured: any): string | undefined {
  if (structured?.schema === "narada.mcp_loader.tool_result.v1") {
    const child = structured.result?.structuredContent ?? structured.result;
    if (child === undefined) return undefined;
    const bodyOnly = bodyOnlyProjectionText(child);
    if (bodyOnly !== undefined) return bodyOnly;
    if (isOutputPage(child) && typeof child.output_text === "string") {
      const projected = projectOutputPageTextForModel(child.output_text);
      if (projected !== child.output_text) return projected;
      const pageIsIncomplete = child.truncated === true
        || child.output_truncated === true
        || typeof child.next_offset === "number";
      if (pageIsIncomplete) {
        const fallback = projectMcpLoaderToolResultForModel(structured);
        if (fallback !== undefined) return JSON.stringify(fallback);
      }
      return projected;
    }
    return JSON.stringify(loaderControlPlaneProjectionForModel(child) ?? child);
  }
  const candidates = [structured, structured?.result, structured?.result?.structuredContent, structured?.result?.result];
  for (const candidate of candidates) {
    const bodyOnly = bodyOnlyProjectionText(candidate);
    if (bodyOnly !== undefined) return bodyOnly;
    if (isOutputPage(candidate) && typeof candidate?.output_text === "string") return projectOutputPageTextForModel(candidate.output_text);
    const controlPlaneProjection = loaderControlPlaneProjectionForModel(candidate);
    if (controlPlaneProjection !== undefined) return JSON.stringify(controlPlaneProjection);
  }
  return undefined;
}

function controlPlaneProjectionText(structured: any): string | undefined {
  const leaseBatchProjection = projectSchemaLeaseBatchForModel(structured);
  if (leaseBatchProjection !== undefined) return JSON.stringify(leaseBatchProjection);
  if (structured?.schema === "narada.mcp_loader.schema_lease.v1") {
    const projection: any = {
      schema: structured.schema,
      status: structured.status,
      tool_name: structured.tool_name,
      schema_lease: structured.schema_lease,
    };
    for (const key of ["connection_id", "surface_id"]) {
      if (typeof structured[key] === "string") projection[key] = structured[key];
    }
    if (structured.input_contract !== undefined) projection.input_contract = structured.input_contract;
    return JSON.stringify(projection);
  }
  if (structured?.schema === "narada.mcp_loader.site_tool_inventory_check.v1") {
    const findings = Array.isArray(structured.findings)
      ? structured.findings.map((finding: any) => {
          const concise: any = {
            surface_id: finding.surface_id,
            status: finding.status,
            declared_count: finding.declared_count,
            observed_count: finding.observed_count,
          };
          for (const key of ["missing_from_fabric", "extra_in_fabric", "duplicate_declared_tools", "duplicate_observed_tools", "unclassified_observed_tools"]) {
            if (Array.isArray(finding[key]) && finding[key].length > 0) concise[key] = finding[key];
          }
          return concise;
        })
      : [];
    return JSON.stringify({
      schema: structured.schema,
      status: structured.status,
      observation_coverage: structured.observation_coverage,
      checked_surface_count: structured.checked_surface_count,
      violation_count: structured.violation_count,
      finding_status_counts: structured.finding_status_counts,
      observation_ref: structured.observation_ref,
      findings,
    });
  }
  return undefined;
}

function mutationReceiptProjectionText(structured: any): string | undefined {
  const projection = projectMutationReceiptForModel(structured);
  return projection === undefined ? undefined : JSON.stringify(projection);
}

function modelContentProjection(result: any, content: any[]): any[] {
  const structuredProjection = modelProjectionTextFromStructured(result?.structuredContent);
  if (structuredProjection !== undefined) return [{ type: "text", text: structuredProjection }];
  const controlPlaneProjection = controlPlaneProjectionText(result?.structuredContent);
  if (controlPlaneProjection !== undefined) return [{ type: "text", text: controlPlaneProjection }];
  const mutationReceiptProjection = mutationReceiptProjectionText(result?.structuredContent);
  if (mutationReceiptProjection !== undefined) return [{ type: "text", text: mutationReceiptProjection }];
  if (result?.structuredContent !== undefined) return content;
  for (const block of Array.isArray(content) ? content : []) {
    if (block?.type !== "text" || typeof block.text !== "string") continue;
    try {
      const textProjection = modelProjectionTextFromStructured(JSON.parse(block.text));
      if (textProjection !== undefined) return [{ type: "text", text: textProjection }];
    } catch {
      // Non-JSON text remains the authoritative projection for this result.
    }
  }
  return content;
}

function preservesDeliveredContent(result: any): boolean {
  return result?.structuredContent?.content_delivery?.format === "filesystem_read_text"
    && Array.isArray(result?.content)
    && result.content.some((block: any) => block?.type === "text" && typeof block.text === "string");
}

const MAX_MODEL_VISIBLE_RESULT_CHARS = 8_000;

type ToolResultView = "compact" | "single-line" | "model-visible" | "full-output" | "hide";
const TOOL_RESULT_VIEWS: ToolResultView[] = ["compact", "single-line", "model-visible", "full-output", "hide"];
const TOOL_RESULT_VIEW_SHORTCUT = "f8";
const TOOL_RESULT_VIEW_SHORTCUT_ALIASES = ["f8", "ctrl+shift+m"];

function boundedModelContent(
  result: any,
  content: any[],
  rawText: string,
  fullOutputText: string,
): { content: any[]; expandedText: string | null; truncated: boolean } {
  const modelText = resultText({ content });
  if (modelText.length <= MAX_MODEL_VISIBLE_RESULT_CHARS) {
    return { content, expandedText: fullOutputText !== modelText ? fullOutputText : null, truncated: false };
  }
  const structured = result?.structuredContent ?? {};
  const reference = structured.output_ref ?? structured.ref ?? structured.details_ref ?? structured.result?.output_ref ?? null;
  const reader = structured.reader_tool ?? structured.details_reader ?? structured.result?.reader_tool ?? null;
  const continuation = structured.result?.next_offset ?? structured.next_offset ?? structured.continuation ?? null;
  const summary = {
    schema: structured.schema ?? "narada.mcp_result.bounded_projection.v1",
    status: structured.status ?? (result?.isError === true ? "error" : "ok"),
    full_output_char_length: fullOutputText.length,
    model_visible_truncated: true,
    output_ref: reference,
    reader_tool: reader,
    next_offset: continuation,
    remediation: reference && reader
      ? `Read bounded pages with ${reader} using output_ref ${reference}.`
      : "Retry with a smaller limit or a narrower range; the full result remains available in Pi via Ctrl+O.",
  };
  return { content: [{ type: "text", text: JSON.stringify(summary) }], expandedText: fullOutputText || rawText, truncated: true };
}

function hiddenComponent(): { render: (width: number) => string[]; invalidate: () => void } {
  return { render: () => [], invalidate: () => {} };
}

function textComponent(text: string): { render: (width: number) => string[] } {
  return {
    render(width: number): string[] {
      const lineWidth = Math.max(1, width);
      return text.split("\n").flatMap((line) => {
        if (line.length === 0) return [""];
        const rendered: string[] = [];
        let current = "";
        let visibleWidth = 0;
        for (let offset = 0; offset < line.length;) {
          if (line.charCodeAt(offset) === 0x1b) {
            const sequence = line.slice(offset).match(/^\x1b(?:\[[0-?]*[ -/]*[@-~]|\][^\x07]*(?:\x07|\x1b\\))/)?.[0];
            if (!sequence) {
              offset += 1;
              continue;
            }
            current += sequence;
            offset += sequence.length;
            continue;
          }
          const character = String.fromCodePoint(line.codePointAt(offset)!);
          if (visibleWidth === lineWidth) {
            rendered.push(current);
            current = "";
            visibleWidth = 0;
          }
          current += character;
          visibleWidth += 1;
          offset += character.length;
        }
        if (current.length > 0 || rendered.length === 0) rendered.push(current);
        return rendered;
      });
    },
  };
}

function mutedText(theme: any, text: string): string {
  return typeof theme?.fg === "function" ? theme.fg("muted", text) : text;
}

function resultViewHeader(view: ToolResultView, characterCount: number, nextView: ToolResultView): string {
  return `${view} · ${compactQuantity(characterCount)} ${characterCount === 1 ? "character" : "characters"} — ${TOOL_RESULT_VIEW_SHORTCUT}: ${nextView}`;
}

__NARADA_MCP_RESULT_PRESENTATION__
function carrierRoutingGuidance(serverName: string, toolName: string): string {
  if (serverName === "structured-command" && toolName.startsWith("structured_command_")) {
    return " Git is not a structured-command fallback: activate the current Site's <site-id>-git binding through mcp-loader, inspect the exact Git tool for a lease, and call that binding.";
  }
  if (serverName === "mcp-loader") {
    return " Site-local Git is lazy: activate <site-id>-git at the repository Site root; do not send git through structured-command.";
  }
  return "";
}

class McpClient {
  readonly config: ServerConfig;
  readonly child: ChildProcessWithoutNullStreams;
  private nextId = 1;
  private pending = new Map<number, {
    resolve: (value: any) => void;
    reject: (error: Error) => void;
    timer: ReturnType<typeof setTimeout>;
  }>();
  private stderrTail = "";

  constructor(config: ServerConfig) {
    this.config = config;
    this.child = spawn(config.command, config.args, {
      env: process.env,
      stdio: ["pipe", "pipe", "pipe"],
      windowsHide: true,
    });
    this.child.stderr.setEncoding("utf8");
    this.child.stderr.on("data", (chunk: string) => {
      this.stderrTail = (this.stderrTail + chunk).slice(-8192);
    });
    createInterface({ input: this.child.stdout }).on("line", (line) => {
      if (!line.trim()) return;
      let message: JsonRpcResponse;
      try {
        message = JSON.parse(line);
      } catch {
        this.failAll(new Error(`${config.name}: invalid JSON-RPC response`));
        return;
      }
      if (typeof message.id !== "number") return;
      const request = this.pending.get(message.id);
      if (!request) return;
      this.pending.delete(message.id);
      clearTimeout(request.timer);
      if (message.error) {
        request.reject(new Error(`${config.name}: ${message.error.message ?? "MCP request failed"}`));
      } else {
        request.resolve(message.result);
      }
    });
    this.child.once("error", (error) => this.failAll(error));
    this.child.once("exit", (code, signal) => {
      this.failAll(new Error(
        `${config.name}: MCP process exited (code=${code}, signal=${signal})${this.stderrTail ? `: ${this.stderrTail}` : ""}`,
      ));
    });
  }

  private failAll(error: Error): void {
    for (const request of this.pending.values()) {
      clearTimeout(request.timer);
      request.reject(error);
    }
    this.pending.clear();
  }

  notify(method: string, params?: unknown): void {
    this.child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method, ...(params === undefined ? {} : { params }) }) + "\n");
  }

  request(method: string, params: unknown, timeoutMs = this.config.startupTimeoutMs, signal?: AbortSignal): Promise<any> {
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        signal?.removeEventListener("abort", abort);
        reject(new Error(`${this.config.name}: ${method} timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      const abort = () => {
        this.pending.delete(id);
        clearTimeout(timer);
        this.notify("notifications/cancelled", { requestId: id, reason: "Pi tool call aborted" });
        reject(new Error(`${this.config.name}: ${method} aborted`));
      };
      if (signal?.aborted) return abort();
      signal?.addEventListener("abort", abort, { once: true });
      this.pending.set(id, {
        timer,
        resolve: (value) => {
          signal?.removeEventListener("abort", abort);
          resolve(value);
        },
        reject: (error) => {
          signal?.removeEventListener("abort", abort);
          reject(error);
        },
      });
      this.child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n");
    });
  }

  async initialize(): Promise<Array<{ name: string; description?: string; inputSchema?: object }>> {
    await this.request("initialize", {
      protocolVersion: PROTOCOL_VERSION,
      capabilities: {},
      clientInfo: { name: "narada-pi-carrier", version: "1" },
    });
    this.notify("notifications/initialized");
    const listed = await this.request("tools/list", {});
    if (!Array.isArray(listed?.tools)) {
      throw new Error(`${this.config.name}: tools/list returned no tools array`);
    }
    return listed.tools;
  }

  close(): void {
    this.failAll(new Error(`${this.config.name}: session closed`));
    if (!this.child.killed) this.child.kill();
  }
}

export default function naradaMcpCarrier(pi: any): void {
  let clients: McpClient[] = [];
  let started = false;
  let toolResultView: ToolResultView = "compact";
  let naradaSessionIdentityState: NaradaSessionIdentityState | null = null;

  const currentSessionId = (ctx: any): string => String(ctx?.sessionManager?.getSessionId?.() ?? "ephemeral");
  const effectiveNaradaIdentity = (): EffectiveNaradaIdentity | null => {
    if (naradaSessionIdentityState?.status === "cleared") return null;
    if (naradaSessionIdentityState?.status === "admitted") return { identity: naradaSessionIdentityState.identity, source: "operator_slash_command" };
    const identity = normalizeNaradaIdentity(startupAuthority(SERVERS.filter(shouldBootstrapServer)).identity);
    return identity ? { identity, source: "carrier_admission" } : null;
  };
  const restoreNaradaSessionIdentity = (ctx: any): void => {
    naradaSessionIdentityState = null;
    const sessionId = currentSessionId(ctx);
    for (const entry of ctx?.sessionManager?.getBranch?.() ?? []) {
      if (entry?.type !== "custom" || ![NARADA_SESSION_IDENTITY_ENTRY, LEGACY_MARICI_SESSION_IDENTITY_ENTRY].includes(entry?.customType)) continue;
      const data = entry.data ?? {};
      if (data.sessionId !== sessionId) continue;
      const identity = normalizeNaradaIdentity(data.identity);
      naradaSessionIdentityState = identity
        ? { status: "admitted", identity, sessionId, changedAt: String(data.changedAt ?? data.admittedAt ?? ""), source: "operator_slash_command" }
        : { status: "cleared", identity: null, sessionId, changedAt: String(data.changedAt ?? data.clearedAt ?? ""), source: "operator_slash_command" };
    }
    const effective = effectiveNaradaIdentity();
    ctx?.ui?.setStatus?.("narada-session-identity", effective ? `Narada: ${effective.identity}` : undefined);
  };

  const naradaIdentityCommand = async (args: string, ctx: any, legacy = false) => {
    if (legacy) ctx?.ui?.notify?.("/marici-identity is deprecated; use /narada-identity.", "warning");
    const requested = args.trim();
    if (requested === "status") {
      const effective = effectiveNaradaIdentity();
      ctx?.ui?.notify?.(effective ? `Mechanically admitted Narada identity: ${effective.identity} (${effective.source}).` : "No mechanically admitted Narada identity for this session.", effective ? "info" : "warning");
      return;
    }
    if (requested === "clear") {
      await ctx.waitForIdle?.();
      naradaSessionIdentityState = { status: "cleared", identity: null, sessionId: currentSessionId(ctx), changedAt: new Date().toISOString(), source: "operator_slash_command" };
      pi.appendEntry(NARADA_SESSION_IDENTITY_ENTRY, naradaSessionIdentityState);
      ctx?.ui?.setStatus?.("narada-session-identity", undefined);
      ctx?.ui?.notify?.("Cleared all mechanically admitted Narada identity for this Pi session, including carrier fallback.", "info");
      pi.events.emit?.("narada:mcp:identity-changed", naradaSessionIdentityState);
      return;
    }
    const candidate = requested.startsWith("set ") ? requested.slice(4).trim() : requested;
    const entered = candidate || (ctx?.hasUI ? await ctx.ui.input("Narada session identity", "identity") : "");
    if (!entered) return;
    const identity = normalizeNaradaIdentity(entered);
    if (!identity) {
      ctx?.ui?.notify?.("Invalid Narada identity. Use 1-200 ASCII letters, digits, dot, underscore, or hyphen; the first character must be alphanumeric.", "error");
      return;
    }
    await ctx.waitForIdle?.();
    naradaSessionIdentityState = { status: "admitted", identity, sessionId: currentSessionId(ctx), changedAt: new Date().toISOString(), source: "operator_slash_command" };
    pi.appendEntry(NARADA_SESSION_IDENTITY_ENTRY, naradaSessionIdentityState);
    ctx?.ui?.setStatus?.("narada-session-identity", `Narada: ${identity}`);
    ctx?.ui?.notify?.(`Mechanically admitted ${identity} for this Pi session. Identity does not grant task-claim, graph-mutation, or publication authority.`, "info");
    pi.events.emit?.("narada:mcp:identity-changed", naradaSessionIdentityState);
  };

  pi.registerCommand("narada-identity", {
    description: "Set, inspect, or clear the mechanically admitted Narada identity for this Pi session",
    handler: (args: string, ctx: any) => naradaIdentityCommand(args, ctx),
  });

  const cycleToolResultView = async (ctx: any): Promise<void> => {
    const previousView = toolResultView;
    const currentIndex = TOOL_RESULT_VIEWS.indexOf(toolResultView);
    toolResultView = TOOL_RESULT_VIEWS[(currentIndex + 1) % TOOL_RESULT_VIEWS.length];
    if (toolResultView === "full-output") {
      ctx?.ui?.setToolsExpanded?.(true);
    } else if (previousView === "full-output") {
      ctx?.ui?.setToolsExpanded?.(false);
    } else {
      // Pi's public UI API exposes only a boolean expansion state. Toggle
      // through true so the host rebuilds rows even when the previous state
      // was false (notably when leaving the hide view).
      ctx?.ui?.setToolsExpanded?.(true);
      ctx?.ui?.setToolsExpanded?.(false);
    }
  };
  for (const shortcut of TOOL_RESULT_VIEW_SHORTCUT_ALIASES) {
    pi.registerShortcut?.(shortcut, {
      description: "Cycle MCP tool output: compact, single-line, model-visible, full-output, hide",
      handler: cycleToolResultView,
    });
  }
  pi.registerCommand("marici-identity", {
    description: "Deprecated alias for /narada-identity",
    handler: (args: string, ctx: any) => naradaIdentityCommand(args, ctx, true),
  });

  pi.on("before_agent_start", (event: any) => {
    const effective = effectiveNaradaIdentity();
    if (!effective) return;
    const provenance = effective.source === "operator_slash_command" ? "The operator admitted it via /narada-identity." : "The carrier admission supplied it.";
    return {
      systemPrompt: `${event.systemPrompt}\n\nSession identity: ${effective.identity} is mechanically admitted for this Pi session. ${provenance} Use it as recipient, participant, or actor only where the owning surface accepts that identity. This identity does not itself grant task-claim, graph-mutation, or publication authority.`,
    };
  });

  const MARICI_INBOX_PAGE_SIZE = 100;
  const MARICI_INBOX_MAX_PAGES = 41;
  const pollMariciInbox = async (request: NaradaMariciInboxPollRequest): Promise<void> => {
    try {
      const client = clients.find((candidate) => candidate.config.name === "mcp-loader");
      if (!client) throw new Error("mcp-loader is not attached");
      const recipientIdentity = effectiveNaradaIdentity()?.identity;
      if (!recipientIdentity) throw new Error("no mechanically admitted Marici recipient identity; use /narada-identity set marici.Name");
      const inspection = await client.request("tools/call", {
        name: "mcp_loader_inspect_binding_tool",
        arguments: {
          site_root: request.siteRoot,
          binding_id: "marici-epistemic-graph",
          tool_name: "epistemic_graph_query",
        },
      }, 10_000);
      const leaseEnvelope = inspection?.structuredContent ?? {};
      const schemaLease = leaseEnvelope?.schema_lease;
      if (typeof schemaLease !== "string" || !schemaLease) throw new Error("epistemic graph query lease unavailable");
      const sequences: number[] = [];
      let count = 0;
      for (let page = 0; page < MARICI_INBOX_MAX_PAGES; page += 1) {
        const called = await client.request("tools/call", {
          name: "mcp_loader_call_binding_tool",
          arguments: {
            site_root: request.siteRoot,
            binding_id: "marici-epistemic-graph",
            tool_name: "epistemic_graph_query",
            schema_lease: schemaLease,
            arguments: {
              kinds: ["narada.epistemic:communication", "marici:communication", "communication"],
              recipient: recipientIdentity,
              after_sequence: request.sinceSequence,
              include_body: false,
              compact: true,
              limit: MARICI_INBOX_PAGE_SIZE,
              offset: page * MARICI_INBOX_PAGE_SIZE,
            },
          },
        }, 15_000);
        const loaderEnvelope = called?.structuredContent ?? {};
        const query = loaderEnvelope?.result?.structuredContent ?? loaderEnvelope?.result ?? {};
        if (query?.schema !== "narada.epistemic.query.v1" || !Array.isArray(query?.items)) {
          throw new Error("epistemic graph returned no bounded communication page");
        }
        count += query.items.length;
        sequences.push(...query.items
          .map((item: any) => typeof item?.event_id === "string"
            ? Number(item.event_id.match(/^ev-(\d+)-/)?.[1] ?? NaN)
            : NaN)
          .filter((value: number) => Number.isSafeInteger(value) && value >= 0));
        if (query.items.length < MARICI_INBOX_PAGE_SIZE) break;
        if (page + 1 >= MARICI_INBOX_MAX_PAGES) throw new Error("Marici inbox count exceeded the 4096-message polling bound");
      }
      const newCursor = sequences.length > 0 ? Math.max(request.sinceSequence, ...sequences) : request.sinceSequence;
      request.resolve({
        count,
        previousCursor: request.sinceSequence,
        newCursor,
        source: "epistemic_graph_communication",
      });
    } catch (error) {
      request.reject(error instanceof Error ? error : new Error(String(error)));
    }
  };
  pi.events.on(NARADA_MARICI_INBOX_POLL_EVENT, pollMariciInbox);

  pi.on("session_start", async (_event: unknown, ctx: any) => {
    toolResultView = "compact";
    restoreNaradaSessionIdentity(ctx);
    if (started) return;
    started = true;
    const nextClients: McpClient[] = [];
    let startupRuntime: StartupRuntime = { loader: "unknown", proxy: "unknown" };
    const bootstrapConfigs = SERVERS.filter(shouldBootstrapServer);
    const authority = startupAuthority(bootstrapConfigs);
    const effective = effectiveNaradaIdentity();
    if (effective) authority.identity = effective.identity;
    ctx?.ui?.notify?.(
      startupDiagnostic(authority, {
        mcp: "loading",
        runtime: { loader: "checking", proxy: "checking" },
        remediation: "waiting for mcp-loader initialization",
      }),
      "info",
    );
    try {
      const inventories: Array<{ client: McpClient; tools: any[]; runtime: StartupRuntime }> = [];
      for (const config of bootstrapConfigs) {
        const client = new McpClient(config);
        try {
          const tools = await client.initialize();
          inventories.push({
            client,
            tools,
            runtime: await inspectStartupRuntime(client, tools),
          });
          nextClients.push(client);
        } catch (error) {
          client.close();
          const message = error instanceof Error ? error.message : String(error);
          ctx?.ui?.notify?.(`Narada MCP server ${config.name} failed: ${message}`, "warning");
        }
      }
      if (inventories.length === 0) {
        throw new Error("No admitted MCP server completed startup");
      }

      startupRuntime = inventories.reduce<StartupRuntime>(
        (current, inventory) => ({
          loader: inventory.runtime.loader !== "unknown" ? inventory.runtime.loader : current.loader,
          proxy: inventory.runtime.proxy !== "unknown" ? inventory.runtime.proxy : current.proxy,
        }),
        { loader: "unknown", proxy: "unknown" },
      );

      const schemaDiagnostics = inventories.map(({ client, tools }) => ({
        server: client.config.name,
        toolCount: tools.length,
        schemaChars: tools.reduce(
          (total, tool) => total + JSON.stringify(tool?.inputSchema ?? {}).length,
          0,
        ),
      }));
      const bootstrapToolCount = schemaDiagnostics.reduce((total, row) => total + row.toolCount, 0);
      const bootstrapSchemaChars = schemaDiagnostics.reduce((total, row) => total + row.schemaChars, 0);
      if (bootstrapToolCount > MAX_BOOTSTRAP_TOOLS || bootstrapSchemaChars > MAX_BOOTSTRAP_SCHEMA_CHARS) {
        throw new Error(`narada_pi_bootstrap_context_budget_exceeded:${JSON.stringify({
          bootstrapToolCount,
          bootstrapSchemaChars,
          maxBootstrapTools: MAX_BOOTSTRAP_TOOLS,
          maxBootstrapSchemaChars: MAX_BOOTSTRAP_SCHEMA_CHARS,
          servers: schemaDiagnostics,
        })}`);
      }

      const existing = new Set((pi.getAllTools?.() ?? []).map((tool: any) => tool.name));
      const counts = new Map<string, number>();
      for (const { client, tools } of inventories) {
        for (const tool of tools) {
          if (typeof tool?.name !== "string" || !tool.name) {
            throw new Error(`${client.config.name}: tools/list contained an invalid tool name`);
          }
          counts.set(tool.name, (counts.get(tool.name) ?? 0) + 1);
        }
      }

      const exposed = new Set<string>();
      for (const { client, tools } of inventories) {
        for (const tool of tools) {
          const serverPrefix = client.config.name.replace(/[^A-Za-z0-9_-]/g, "_");
          const exposedName = counts.get(tool.name) === 1 && !existing.has(tool.name)
            ? tool.name
            : `${serverPrefix}__${tool.name}`;
          if (existing.has(exposedName) || exposed.has(exposedName)) {
            throw new Error(`Narada MCP qualified tool name collision: ${exposedName}`);
          }
          exposed.add(exposedName);
          pi.registerTool({
            name: exposedName,
            label: tool.title ?? exposedName,
            description: `${tool.description ?? "MCP tool"} (server: ${client.config.name}; MCP name: ${tool.name}).${carrierRoutingGuidance(client.config.name, tool.name)}`,
            parameters: tool.inputSchema ?? { type: "object", additionalProperties: true },
            renderCall: (_args: any, theme: any) => toolResultView === "single-line" || toolResultView === "hide"
              ? hiddenComponent()
              : textComponent(theme.fg("toolTitle", theme.bold(tool.name))),
            execute: async (_toolCallId: string, params: unknown, signal: AbortSignal) => {
              const result = await client.request("tools/call", { name: tool.name, arguments: params ?? {} }, 120000, signal);
              const rawText = resultText(result);
              const content = preservesDeliveredContent(result)
                ? result.content
                : result?.structuredContent !== undefined
                ? [{ type: "text", text: JSON.stringify(result.structuredContent) }]
                : Array.isArray(result?.content) && result.content.length > 0
                  ? result.content
                  : [{ type: "text", text: JSON.stringify(result ?? null) }];
              const fullOutputText = resultText({ content });
              const modelContent = modelContentProjection(result, content);
              const bounded = boundedModelContent(result, modelContent, rawText, fullOutputText);
              const modelVisibleText = resultText({ content: bounded.content });
              return {
                content: bounded.content,
                details: {
                  mcpServer: client.config.name,
                  isError: result?.isError === true,
                  structuredSchema: result?.structuredContent?.schema ?? null,
                  continuation: result?.structuredContent?.result?.next_offset ?? result?.structuredContent?.next_offset ?? null,
                  fullOutputCharLength: fullOutputText.length,
                  modelVisibleCharLength: modelVisibleText.length,
                  modelVisibleTruncated: bounded.truncated,
                  uiSummary: summarizeMcpResult(result, fullOutputText, modelVisibleText),
                  collapseByDefault: collapseMcpResultByDefault(),
                  expandedText: bounded.expandedText,
                },
                isError: result?.isError === true,
              };
            },
            renderResult: (result: any, options: { expanded: boolean }, theme: any) => {
              if (toolResultView === "hide") return hiddenComponent();
              const modelVisibleText = resultText(result);
              const fullText = result?.details?.expandedText ?? modelVisibleText;
              const view: ToolResultView = toolResultView === "compact" && options.expanded
                ? "full-output"
                : toolResultView;
              const nextView = TOOL_RESULT_VIEWS[(TOOL_RESULT_VIEWS.indexOf(toolResultView) + 1) % TOOL_RESULT_VIEWS.length];
              if (view === "full-output") {
                return textComponent(`${resultViewHeader(view, fullText.length, nextView)}\n${fullText || JSON.stringify(result?.details ?? null)}`);
              }
              if (view === "model-visible") {
                return textComponent(`${resultViewHeader(view, modelVisibleText.length, nextView)}\n${modelVisibleText || JSON.stringify(result?.details ?? null)}`);
              }
              const summary = result?.details?.uiSummary ?? summarizeMcpResult(result, fullText, modelVisibleText);
              const modelVisibleSize = `model-visible ${compactQuantity(modelVisibleText.length)} ${modelVisibleText.length === 1 ? "character" : "characters"}`;
              const summaryWithModelVisibleSize = summary.includes("model-visible")
                ? summary
                : `${summary} · ${modelVisibleSize}`;
              return textComponent(mutedText(theme, `${summaryWithModelVisibleSize} — ${TOOL_RESULT_VIEW_SHORTCUT}: ${nextView}`));
            },
          });
        }
      }
      clients = nextClients;
      ctx?.ui?.notify?.(
        startupDiagnostic(authority, {
          mcp: "attached",
          runtime: startupRuntime,
          remediation: startupRemediation(authority, startupRuntime, "attached"),
        }),
        "info",
      );
      ctx?.ui?.notify?.(
        `Narada MCP: ${exposed.size} bootstrap tools from ${clients.length} servers (${bootstrapSchemaChars} schema chars); Site capabilities are lazy through mcp-loader`,
        "info",
      );
    } catch (error) {
      for (const client of nextClients) client.close();
      clients = [];
      started = false;
      ctx?.ui?.notify?.(
        startupDiagnostic(authority, {
          mcp: "failed",
          runtime: startupRuntime,
          remediation: startupRemediation(authority, startupRuntime, "failed"),
        }),
        "warning",
      );
      const message = error instanceof Error ? error.message : String(error);
      ctx?.ui?.notify?.(`Narada MCP startup failed: ${message}`, "error");
      throw error;
    }
  });

  pi.on("session_shutdown", () => {
    toolResultView = "compact";
    for (const client of clients) client.close();
    clients = [];
    started = false;
    pi.events.off?.(NARADA_MARICI_INBOX_POLL_EVENT, pollMariciInbox);
  });
}
