// Generated by Narada carrier materialization. Do not edit.
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createInterface } from "node:readline";

type ServerConfig = {
  name: string;
  command: string;
  args: string[];
  enabled: boolean;
  startupTimeoutMs: number;
};

type JsonRpcResponse = {
  id?: number;
  result?: any;
  error?: { code?: number; message?: string; data?: unknown };
};

const SERVERS: ServerConfig[] = __NARADA_PI_MCP_SERVERS__;
const PROTOCOL_VERSION = "2026-07-28";

class McpClient {
  readonly config: ServerConfig;
  readonly child: ChildProcessWithoutNullStreams;
  private nextId = 1;
  private pending = new Map<number, {
    resolve: (value: any) => void;
    reject: (error: Error) => void;
    timer: ReturnType<typeof setTimeout>;
  }>();
  private stderrTail = "";

  constructor(config: ServerConfig) {
    this.config = config;
    this.child = spawn(config.command, config.args, {
      env: process.env,
      stdio: ["pipe", "pipe", "pipe"],
      windowsHide: true,
    });
    this.child.stderr.setEncoding("utf8");
    this.child.stderr.on("data", (chunk: string) => {
      this.stderrTail = (this.stderrTail + chunk).slice(-8192);
    });
    createInterface({ input: this.child.stdout }).on("line", (line) => {
      if (!line.trim()) return;
      let message: JsonRpcResponse;
      try {
        message = JSON.parse(line);
      } catch {
        this.failAll(new Error(`${config.name}: invalid JSON-RPC response`));
        return;
      }
      if (typeof message.id !== "number") return;
      const request = this.pending.get(message.id);
      if (!request) return;
      this.pending.delete(message.id);
      clearTimeout(request.timer);
      if (message.error) {
        request.reject(new Error(`${config.name}: ${message.error.message ?? "MCP request failed"}`));
      } else {
        request.resolve(message.result);
      }
    });
    this.child.once("error", (error) => this.failAll(error));
    this.child.once("exit", (code, signal) => {
      this.failAll(new Error(
        `${config.name}: MCP process exited (code=${code}, signal=${signal})${this.stderrTail ? `: ${this.stderrTail}` : ""}`,
      ));
    });
  }

  private failAll(error: Error): void {
    for (const request of this.pending.values()) {
      clearTimeout(request.timer);
      request.reject(error);
    }
    this.pending.clear();
  }

  notify(method: string, params?: unknown): void {
    this.child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method, ...(params === undefined ? {} : { params }) }) + "\n");
  }

  request(method: string, params: unknown, timeoutMs = this.config.startupTimeoutMs, signal?: AbortSignal): Promise<any> {
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        signal?.removeEventListener("abort", abort);
        reject(new Error(`${this.config.name}: ${method} timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      const abort = () => {
        this.pending.delete(id);
        clearTimeout(timer);
        this.notify("notifications/cancelled", { requestId: id, reason: "Pi tool call aborted" });
        reject(new Error(`${this.config.name}: ${method} aborted`));
      };
      if (signal?.aborted) return abort();
      signal?.addEventListener("abort", abort, { once: true });
      this.pending.set(id, {
        timer,
        resolve: (value) => {
          signal?.removeEventListener("abort", abort);
          resolve(value);
        },
        reject: (error) => {
          signal?.removeEventListener("abort", abort);
          reject(error);
        },
      });
      this.child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n");
    });
  }

  async initialize(): Promise<Array<{ name: string; description?: string; inputSchema?: object }>> {
    await this.request("initialize", {
      protocolVersion: PROTOCOL_VERSION,
      capabilities: {},
      clientInfo: { name: "narada-pi-carrier", version: "1" },
    });
    this.notify("notifications/initialized");
    const listed = await this.request("tools/list", {});
    if (!Array.isArray(listed?.tools)) {
      throw new Error(`${this.config.name}: tools/list returned no tools array`);
    }
    return listed.tools;
  }

  close(): void {
    this.failAll(new Error(`${this.config.name}: session closed`));
    if (!this.child.killed) this.child.kill();
  }
}

export default function naradaMcpCarrier(pi: any): void {
  let clients: McpClient[] = [];
  let started = false;

  pi.on("session_start", async (_event: unknown, ctx: any) => {
    if (started) return;
    started = true;
    const nextClients: McpClient[] = [];
    try {
      const inventories: Array<{ client: McpClient; tools: any[] }> = [];
      for (const config of SERVERS.filter((server) => server.enabled)) {
        const client = new McpClient(config);
        try {
          inventories.push({ client, tools: await client.initialize() });
          nextClients.push(client);
        } catch (error) {
          client.close();
          const message = error instanceof Error ? error.message : String(error);
          ctx?.ui?.notify?.(`Narada MCP server ${config.name} failed: ${message}`, "warning");
        }
      }
      if (inventories.length === 0) {
        throw new Error("No admitted MCP server completed startup");
      }

      const existing = new Set((pi.getAllTools?.() ?? []).map((tool: any) => tool.name));
      const counts = new Map<string, number>();
      for (const { client, tools } of inventories) {
        for (const tool of tools) {
          if (typeof tool?.name !== "string" || !tool.name) {
            throw new Error(`${client.config.name}: tools/list contained an invalid tool name`);
          }
          counts.set(tool.name, (counts.get(tool.name) ?? 0) + 1);
        }
      }

      const exposed = new Set<string>();
      for (const { client, tools } of inventories) {
        for (const tool of tools) {
          const serverPrefix = client.config.name.replace(/[^A-Za-z0-9_-]/g, "_");
          const exposedName = counts.get(tool.name) === 1 && !existing.has(tool.name)
            ? tool.name
            : `${serverPrefix}__${tool.name}`;
          if (existing.has(exposedName) || exposed.has(exposedName)) {
            throw new Error(`Narada MCP qualified tool name collision: ${exposedName}`);
          }
          exposed.add(exposedName);
          pi.registerTool({
            name: exposedName,
            label: tool.title ?? exposedName,
            description: `${tool.description ?? "MCP tool"} (server: ${client.config.name}; MCP name: ${tool.name})`,
            parameters: tool.inputSchema ?? { type: "object", additionalProperties: true },
            execute: async (_toolCallId: string, params: unknown, signal: AbortSignal) => {
              const result = await client.request("tools/call", { name: tool.name, arguments: params ?? {} }, 120000, signal);
              const content = Array.isArray(result?.content) && result.content.length > 0
                ? result.content
                : [{ type: "text", text: JSON.stringify(result?.structuredContent ?? result ?? null) }];
              return {
                content,
                details: {
                  mcpServer: client.config.name,
                  isError: result?.isError === true,
                  structuredSchema: result?.structuredContent?.schema ?? null,
                  continuation: result?.structuredContent?.result?.next_offset ?? result?.structuredContent?.next_offset ?? null,
                },
                isError: result?.isError === true,
              };
            },
          });
        }
      }
      clients = nextClients;
      ctx?.ui?.notify?.(`Narada MCP: ${exposed.size} tools from ${clients.length} admitted servers`, "info");
    } catch (error) {
      for (const client of nextClients) client.close();
      clients = [];
      started = false;
      const message = error instanceof Error ? error.message : String(error);
      ctx?.ui?.notify?.(`Narada MCP startup failed: ${message}`, "error");
      throw error;
    }
  });

  pi.on("session_shutdown", () => {
    for (const client of clients) client.close();
    clients = [];
    started = false;
  });
}
